### ISSUE TITLE
Consider CostManifest Class (for institution-wide costs)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#184]
While the current CostProfile is probably adequate for the description of one-off, local, or program-specific costs, the burden of repeated descriptions using CostProfile for temporally fixed cross-agent cost structures is too high. Consideration should be given to a new RDF class--ctdl:CostManifest--that is a ***stand-alone*** resource containing an inventory of an agent's cost categories and values. That would provide the means through the resource URI to simply link to the manifest (wherever located) and ingest the data (Linked Data at work!). 

As noted on our call, convening a group of experts to look at the needs/requirements for this particular purpose would be useful (***constrained by a CE use case***)

One benefit *might* be that the manifest could be maintained and hosted by the owning agent thus removing issues of misrepresentation of costs on the CER end.

**Comment by stuartasutton** [comment]
Perhaps an approach like the following might be a good place to start:
![2016-11-11-costmanifest](https://cloud.githubusercontent.com/assets/2939046/20221931/3c53c56e-a7e8-11e6-99fa-b5ab091250ba.png)

**Comment by stuartasutton** [comment]
Then...something like this:
> Credential==currentCostManifest==>CostManifest

**Comment by siuc-nate** [comment]
I especially like the idea of it being hosted externally to the CR - not only does it free us up legally, it also means we can link to a (well-marked-up) cost details page (or data entity) on the organization's website, rather than trying to replicate all of that information in our own system.

**Comment by stuartasutton** [comment]
And yet you would still have access to the data for any CER-related number crunching, displaying etc.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate this is now included in a Google Doc so we can review and plan for expert input  https://docs.google.com/document/d/1IDcy0xvi1hJyoWArXAOchjMto0L_dBn8ijFB1Po03hE/edit?usp=sharing

**Comment by siuc-nate** [comment]
I created this spreadsheet to markup various institutions' CostManifest-style data (via lists of CostProfile data) in the hopes of discovering patterns that might help us refine both CostManifest and CostProfile.
https://docs.google.com/spreadsheets/d/1dexHkddIGPkDnbta8wZP9lqonxXC95Zpv9V8CXdP9gk/edit#gid=0

So far, my observations are:
- We need a property within CostProfile to define additional constraints that are not consistent enough to merit new terms in a proper vocabulary (see #388 and the "Cost Properties" column in the spreadsheet)
- We need additional terms within the Audience vocabulary to explicitly point to current/former military spouses and/or dependents (see #387)
- CostType is almost always "Tuition"
- CostType has a term for "Reexamination" but not "Examination" (unless "StandaloneAssessment" counts?)
- I have not seen many cases where most of the other terms in the CostType vocabulary apply
- As such, I wonder if CostType should actually be a Literal, or if the CostType vocabulary should be reduced to just common/very broad items like "Aggregate Costs", "Tuition", "Application", etc., and leave specific or edge-case items like "ReschedulingFee" and "StudentServicesFee" to the domain of of a Literal such as "costTypeDescription". This would work more or less the same way as the URL-description pairs we've come up with in other parts of the schema. 
- Consider the case where a cost applies to a person who is a citizen of the US, but not a citizen of a given state. Should that CostProfile have "audience:Citizen" or "audience:NonCitizen" (given that "residency:OutOfState" applies in either case)?
- The CostManifest data for [Kaplan University](http://www.kaplanuniversity.edu/paying-school/tuition-reduction.aspx) is a series of 9 PDFs for various combinations of residency, audience, and online/offline.  Each of these contains a very large amount of data (particularly if it were expanded to fit into the CostProfile schema). Is it realistic to expect all of this data to be entered? Certainly, only having to do it once is a strong justification for CostManifest.
- In some ways, it would be nice to be able to define a table within the schema itself.  There is an [existing effort](http://frictionlessdata.io/guides/json-table-schema/) for this, but it is still in development. Plus it would open the door to a lot of complexity and errors in both the schema itself and the interface (as well as anything that hopes to store or display the data)
- The interface for CostProfile in the editor will need to be streamlined and probably custom-built in some regard in order to make entering so much data easier.

**Comment by carlacasilli** [comment]
A few points re this approach:

- this appears to be a brief workable and scalable solution ++
- cost data will be added depending on a few factors, including the inclination of the issuer
- soft or indirect costs most likely will not make it into the data
- QA concerns about the validity of costs entered (understanding that verification of actual costs exists outside the purview of this work). Nevertheless, the question for use exists: how would cost data actually be compared across different credentials and levels of trust?

**Comment by siuc-nate** [comment]
Side Note: I have posted this issue to the Google Group here:
https://groups.google.com/forum/#!topic/credentialenginetech/Xf4XK9WkcbQ

**Comment by siuc-nate** [comment]
@carlacasilli 

>cost data will be added depending on a few factors, including the inclination of the issuer
I'm not sure if you're suggesting this would be good or bad. Can you elaborate? Thanks.

>soft or indirect costs most likely will not make it into the data
Do you have an example of what kind of data this would be?

>QA concerns about the validity of costs entered (understanding that verification of actual costs exists outside the purview of this work). Nevertheless, the question for use exists: how would cost data actually be compared across different credentials and levels of trust?
I'm not sure I understand the question. The CostManifest data would be maintained at the organization level and referenced by 1-n credentials.  So, that data would look/be identical for any credential that references it if you were comparing credentials.  The trust would have to be in the organization providing the CostManifest (if I'm understanding you correctly).

**Comment by siuc-nate** [comment]
Proposed action:

**Create:**
**URI:** ceterms:CostManifest
**Label:** Cost Manifest
**Definition:** A set of costs maintained at the organizational and/or sub-organizational level.
**Comment:** These costs are intended to be referenced by external entities to augment the process of describing the costs for those entities.
**Properties:**
- ceterms:description
- ceterms:name
- ceterms:startDate
- ceterms:endDate
- ceterms:estimatedCost
- ceterms:costDetails (see #389)

**Comment by stuartasutton** [comment]
Note quite sure how "external entities" is being used. Example? While supporting external entities wanting to reference the manifest, it is really important to internal entities...

**Comment by siuc-nate** [comment]
By external I meant "anything outside of the manifest".  So, any of the credentials, assessments, learning opportunities, etc., that would point to the manifest would be external to it.

**Comment by siuc-nate** [comment]
**Create:**
**URI:** ceterms:CostManifest
**Label:** Cost Manifest
**Definition:** A set of costs maintained at the organizational and/or sub-organizational level.
**Comment:** These costs are intended to be referenced by other resources to augment the process of describing the costs for those entities.
**Properties:**
- ceterms:description
- ceterms:name
- ceterms:startDate
- ceterms:endDate
- ceterms:estimatedCost
- ceterms:costDetails

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.

**Comment by siuc-nate** [comment]
Unfortunately, it seems that the "hasCostManifest" and "commonCosts" properties fell through the cracks on this one - the data below is based on "hasConditionManifest" and "commonConditions" properties:

Proposal:
**Create:**
**URI:** ceterms:hasCostManifest
**Label:** Has Cost Manifest
**Definition:** The resource being referenced describes a set of cost data maintained by the agent being described.
**Domain:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization
**Range:** ceterms:CostManifest

**Create:**
**URI:** ceterms:commonCosts
**Label:** Has Cost Manifest
**Definition:** The resource being referenced describes a set of common costs applicable to the resource being described.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile, ceterms:ConditionProfile
**Range:** ceterms:CostManifest

@stuartasutton @jkitchensSIUC please let me know if you see anything wrong with these; if not, please respond so we can get these taken care of. Thanks.

**Comment by cwd-mparsons** [comment]
This looks fine to me

**Comment by stuartasutton** [comment]
Looks ok to me as well.

**Comment by siuc-nate** [comment]
Thanks.  I'll re-close this, then.
