### ISSUE TITLE
ceterms:ConditionManifest Class Proposal

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#247]
The condition profile is similar to the cost profile insomuch that for degrees the conditions are institutional with potential for some additional requirements specific to the credential.  Like cost, we should talk about and likely prioritize a review group to ensure the approach to this profile accommodates both credentials that will have a one-to-one relationship  between conditions and a credential vs. a one to many relationship based on a set of conditions relevant to many credentials.

**Comment by stuartasutton** [comment]
This suggests the possibility of an 'institutional' ConditionManifest as subclass of ConditionProfile in the manner of our nascent CostManifest.  We need to consider (per our discussion yesterday of entities with URI) whether being able to create a ConditionProfile for a 'condition set' and then reference it by URI repeatedly would not suffice in most instances.

**Comment by jkitchensSIUC** [comment]
Use/Refer to https://github.com/CredentialTransparencyInitiative/vocabularies/projects/2

**Comment by stuartasutton** [comment]
See also #184 on Cost Manifest. Both should likelt share a general modeling architecture.

**Comment by siuc-nate** [comment]
I have created a visual to help move this forward:
![image](https://cloud.githubusercontent.com/assets/21346519/24269340/dfe53150-0fde-11e7-9b03-614eb57fc4a6.png)

In this, we see that a ConditionManifest (referenced by URI, preferably a resolvable URL) is used in place of a ConditionProfile in various ways (including via a third-party credential) - the benefit being that it prevents duplication of data.  

There is a double-edged sword in that changes to the ConditionManifest will impact everything that links to it; this may or may not be desirable depending on the situation.

**Comment by siuc-nate** [comment]
Per our 3/28/2017 conversation:

We will pursue ConditionManifest more or less as described above, but with one notable difference: Rather than being a ConditionProfile, ConditionManifest will be its own class that contains 1-n ConditionProfiles via the same properties that other entities currently use to point to ConditionProfile:
![image](https://cloud.githubusercontent.com/assets/21346519/24469648/c6078b32-1481-11e7-80d7-f28115c39c5b.png)

This leads to the introduction of a second property, "commonConditions", whose data would be concatenated with the data pointed to by "requires", "recommends", etc. when such data is present. 

The consuming system would essentially reassign the properties (and what they point to) to the entity that points to the ConditionManifest - in other words, it would virtually copy the "requires", "recommends", etc. ConditionProfiles from the ConditionManifest to the root Credential, Assessment, or LearningOpportunity.

Would we also want to allow ConditionProfile properties such as additionalCondition and alternativeCondition to point to ConditionManifest? It would seem to be in line with the intended function of ConditionManifest to do so.

**Comment by jeff-grann** [comment]
Would each credential in the registry have a fully contained serialization? or would tools need to transverse the condition manifests?

**Comment by siuc-nate** [comment]
@jeff-grann The credentials (and other entities) would reference the ConditionManifest by its URI, so that the serialization of that ConditionManifest wouldn't be duplicated between records.  Something like:

```
{ 
   "@type": "ceterms:ConditionManifest",
   "@id": "http://www.credentialengineregistry.org/resources/[someUUID]"
   "ceterms:requires": [
      {
         "@type": "ceterms:ConditionProfile",
         "ceterms:description": "The description of these conditions"
         "...": "...[Other data]"
      }
   ]
}
```
and then
```
{
   "@type": "ceterms:Certificate",
   "ceterms:requires": [
      { "@id": "http://www.credentialengineregistry.org/resources/[someUUID]" }
   ]
}
```
where [someUUID] is the same between examples.

So it would be up to the consuming system to go and harvest the condition manifests that are referenced.

**Comment by siuc-nate** [comment]
Per our 4/4/2017 call:
**URI:** ceterms:ConditionManifest
**Label:** Condition Manifest
**Definition:** A set of conditions maintained at the organizational and/or sub-organizational level.
**Comment:** These conditions are intended to be referenced by external entities to augment the process of describing the conditions for those entities.

**URI:** ceterms:hasConditionManifest
**Label:** Has Condition Manifest
**Definition:** The resource being referenced describes a set of conditions maintained by the agent being described.
**Domain:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization
**Range:** ceterms:ConditionManifest

**URI:** ceterms:commonConditions
**Label:** Common Conditions
**Definition:** The resource being referenced describes a set of common conditions applicable to the resource being described.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
**Range:** ceterms:ConditionManifest

**Comment by siuc-nate** [comment]
Per Stuart's comment here: https://github.com/CredentialEngine/vocabularies/issues/371#issuecomment-292222623
We should also add ceterms:subjectWebpage to this class.  That got me wondering if there are any other properties we'd want, such as:
- ceterms:name
- ceterms:description
- ceterms:jurisdiction
- ceterms:dateEffective

Thoughts?

**Comment by jkitchensSIUC** [comment]
@siuc-nate the purpose of the manifest is to enable organization or sub-organization conditions.  If you look at examples we have, you can see that name, description, subject webpage should definitely be included.

**Comment by stuartasutton** [comment]
+1

**Comment by siuc-nate** [comment]
Action to be taken:

**URI:** ceterms:ConditionManifest
**Label:** Condition Manifest
**Definition:** A set of conditions maintained at the organizational and/or sub-organizational level.
**Comment:** These conditions are intended to be referenced by external entities to augment the process of describing the conditions for those entities.

**URI:** ceterms:hasConditionManifest
**Label:** Has Condition Manifest
**Definition:** The resource being referenced describes a set of conditions maintained by the agent being described.
**Domain:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization
**Range:** ceterms:ConditionManifest

**URI:** ceterms:commonConditions
**Label:** Common Conditions
**Definition:** The resource being referenced describes a set of common conditions applicable to the resource being described.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile, ceterms:ConditionManifest
**Range:** ceterms:ConditionManifest

ceterms:ConditionManifest will be added to the domains of the following properties:
- ceterms:requires
- ceterms:recommends
- ceterms:advancedStandingFrom
- ceterms:preparationFrom
- ceterms:entryCondition
- ceterms:isRequiredFor
- ceterms:isRecommendedFor
- ceterms:isAdvancedStandingFor
- ceterms:isPreparationFor
- ceterms:name
- ceterms:description
- ceterms:subjectWebpage

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
