### ISSUE TITLE
Add Organization to the domain of development, maintenance, and administration process properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#315]
Determine if  there is a need to extend the domains of these to include CredentialOrganization and QACredentialOrganization:

ceterms:developmentProcess
ceterms:maintenanceProcess
ceterms:administrationProcess

**Comment by siuc-nate** [comment]
I'm moving this to the next release, unless it needs to be a part of this one - @jkitchensSIUC please let me know.

**Comment by jkitchensSIUC** [comment]
@siuc-nate if these are all need changes, I prefer they be included with the Feb release.

**Comment by siuc-nate** [comment]
Then here are the proposed actions:

Update ceterms:developmentProcess, ceterms:maintenanceProcess, and ceterms:administrationProcess
Add domains: ceterms:CredentialOrganization, ceterms:QACredentialOrganization

Create ceterms:reviewProcess
Label: Review Process
Definition: A profile of the process by which the resource being described, or aspects of it, are reviewed.
Domain: ceterms:Credential, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:ProcessProfile

Create ceterms:revocationProcess
Label: Revocation Process
Definition: A profile of the process by which the resource being described, or aspects of it, are revoked.
Domain: ceterms:Credential, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:ProcessProfile

Create ceterms:appealProcess
Label: Appeal Process
Definition: A profile of the process by which the resource being described, or aspects of it, are appealed.
Domain: ceterms:Credential, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:ProcessProfile

Create ceterms:complaintProcess
Label: Complaint Process
Definition: A profile of the process by which complaints about the resource being described, or aspects of it, are handled.
Domains: ceterms:Credential, ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:ProcessProfile

If these sound good, I will go ahead and add them.  Please review the definitions carefully and consider any needful usage notes/comments.

Thanks.

**Comment by jkitchensSIUC** [comment]
For these, we'll need input from Bob and Roy so we need to do this one with the April release.

**Comment by stuartasutton** [comment]
Jeanne, then these changes are being held til April release?

**Comment by stuartasutton** [comment]
The proposed actions above look OK to me.

**Comment by stuartasutton** [comment]
On second though, I'm uncertain of the applicability given some of the domains. For example, the domain of these properties are the "thing"...so with something like `appealProcess` with domain of CredentialOrganization, it states that the process describes how you would *appeal the organization*. Huh? How is the thing (organization) revoked? You might revoke something imprimatur of approval granted the organization, but how do you revoke the actual organization. That's the takeaway of the definitions/domains.

`Credential` as domain makes sense to me, not so much the organizations.

**Comment by siuc-nate** [comment]
The intent is to be able to indicate those processes (or perhaps policies?) at the organization level without necessarily relating them to a credential, so perhaps we need companion properties that reflect this (which raises the question of whether or not we need the new properties indicated above, or if we simply need their organization-level equivalents).

**Comment by stuartasutton** [comment]
I clearly understand the desire to make information about an organization's processes in the lifecycle of the resources it creates/manages directly available through that organization's description. But the current definitions of `administrationProcess`, `developmentProcess`, and `maintenanceProcess` do not support it. All definitions speak of processes by which the thing being described is administered, developed, and maintained. 

It seems to me that to expand the domain to include agent types, the properties would need to be significantly generalized with definitions like: 
- "A process by which a resource is administered." 
- "A process by which a resource is developed."
- "A process by which a resource is maintained."

However, this general applicability results in an equally general ambiguity since it would not be clear when used with an organization whether it is talking about administering itself or administering something it controls.

To totally avoid such ambiguity, you'd need new, additional properties with a domain of agent something like: 
- `resourceAdministationProcess`: "A profile of an organization's administrative processes for a resource class it controls." 
- `resourceDevelopmentProcess`: "A profile of an organization's development processes for a resource class it controls."
- `resourceMaintenanceProcess`: "A profile of an organization's maintenance processes for a resource class it controls."

**Comment by siuc-nate** [comment]
To further discussion, a pseudo-proposal: 3 new properties (perhaps the definitions are _too_ broad, but I wanted to be able to point at a specific thing or a class of things, and enable these properties to be added to non-organization entities such as CredentialPerson):

URI: resourceAdministrationProcess
Label: Resource Administration Process
Definition: A resource describing the administration process for a resource (or a class of resources) that is controlled by the resource being described.
Domain: ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:ProcessProfile

URI: resourceDevelopmentProcess
Label: Resource Administration Process
Definition: A resource describing the development process for a resource (or a class of resources) that is controlled by the resource being described.
Domain: ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:ProcessProfile

URI: resourceMaintenanceProcess
Label: Resource Administration Process
Definition: A resource describing the maintenance process for a resource (or a class of resources) that is controlled by the resource being described.
Domain: ceterms:CredentialOrganization, ceterms:QACredentialOrganization
Range: ceterms:ProcessProfile

**Comment by siuc-nate** [comment]
Per our 3/7/2017 discussion:

We will **not** create new properties; the existing properties as defined will work.  Instead, we will continue with the original proposal of adding organization to the domain of the process properties:

**Add:**
> **Subject:** ceterms:administrationProcess
> **Predicate:** rdfs:domain
> **Object:** ceterms:CredentialOrganization

**Add:**
> **Subject:** ceterms:developmentProcess
> **Predicate:** rdfs:domain
> **Object:** ceterms:CredentialOrganization

**Add:**
> **Subject:** ceterms:maintenanceProcess
> **Predicate:** rdfs:domain
> **Object:** ceterms:CredentialOrganization

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
