### ISSUE TITLE
Property serilaizations now end with "meta:targetConceptScheme"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#332]
Nate, please check the property serializations in both turtle and json-ld. I believe all of them now end with this new line that I do not recognize:

Turtle: `meta:targetConceptScheme : .`
JSON-LD: `"meta:targetConceptScheme":[{"@id":":"}]}]}`

**Comment by siuc-nate** [comment]
This should now be fixed.

For what it's worth, it was/is intended to be a URI for the concept scheme intended for use with a given property - otherwise there is no other machine-readable way of indicating it (that I know of).  It was erroneously being included with non-vocabulary-related properties (and thus empty).

**Comment by stuartasutton** [comment]
I'm not sure I understand the purpose, but if the problem is corrected, it's not critical that I know.
