### ISSUE TITLE
Clarify purpose and usage of ceterms:url

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#334]
Refer to http://credreg.net/ctdl/terms/url

Some time ago, we made a number of changes to our use of URL:
https://github.com/CredentialEngine/vocabularies/issues/192

In particular, we removed it from everything but Credential and GeoCoordinates.  However, I am unable to find the discussion where this decision was made or justified; the closest I can find was a post in #110, specifically: https://github.com/CredentialEngine/vocabularies/issues/110#issuecomment-263615160

However, the discussion continues on from that point.  Unfortunately, the discussion also morphs from a discussion of ceterms:url to a discussion of ceterms:subjectWebpage, making it difficult to determine what remains relevant to url.

I believe it had something to do with wanting to be able to point to a credential via URL directly in the CER, but since so many discussions of URL happened outside of github, I cannot be certain.

So, the purpose of this issue is to make sure we still want/need to keep ceterms;url at all, and if so, whether or not it should remain on Credential (and GeoCoordinates).  Being able to point to this issue should help us out later on if/when this question comes up again.

**Comment by stuartasutton** [comment]
Yes, we eliminated the use of `ceterms:url` to denote the webage of the resource being described and created `ceterms:subjectWebpage` to serve that purpose. The comments in #110 do indeed state the rationale (although across several of the comments). Beyond, being ambiguous (e.g., is a `ceterms:url` in a `LearningOpportunityProfile` description the url of the profile (which could easily have a URI) or of the thing being described? Second, `schema:url` has a particular use in markup of an actual URL in text (i.e. `<a href...>`)...not our use case. With CTDL, it is just plain dangerous because it leads to putting a resource URI into a description as a property value of `ceterms:url` as opposed to it being the `@id` of the resource in jsonld.

Now, Michael has pointed out that the last vestigate of `ceterms:url` is with`Credential` and its subclasses (which also already its `ceterms:subjectHomepage`). I suggest retiring it use here as well meaning we don't use `ceterms:url` anywhere..

**Comment by siuc-nate** [comment]
That sounds fine to me - one more thing though: we use it in GeoCoordinates to hold the geonames URL for a given place.  Should we keep it around for that reason or create some other property for that?

**Comment by siuc-nate** [comment]
Per our 3/7/2017 call, we will do the following:

- Deprecate ceterms:uri

- Create ceterms:geoURI
URI: ceterms:geoURI
Label: Geographic URI
Definition: A resource that defines a place
Comment: This may define a place at any scale. Examples include a city, state, region, country, or continent.
Usage Note: It is recommended to use services such as http://www.geonames.org to provide values for this property.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
