### ISSUE TITLE
Remove references to ISO8601 in all date/dateTime properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#370]
ceterms:endTime has the following usage note (Curiously, ceterms:startTime does not):
"Start and end dates and times of the credentialing action (in ISO 8601 date format). For actions that span a period of time, when the action ended."

This usage note should be removed, or at least, the reference to ISO 8601 should be dropped, as the xsd:date is more restrictive than the ISO8601 date - namely in that it requires a full date rather than allowing a partial date.

For the same reason, the definition of ceterms:temporalCoverage should be updated from:
"The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes, either as a DateTime or as a textual string indicating a time period in ISO 8601 time interval format."
to:
"The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes."

**Comment by siuc-nate** [comment]
Actions to be taken:

**Remove**
> **Subject:** ceterms:endTime
> **Predicate:** vann:usageNote
> **Object:** "Start and end dates and times of the credentialing action (in ISO 8601 date format). For actions that span a period of time, when the action ended."

**Remove**
> **Subject:** ceterms:temporalCoverage
> **Predicate:** rdfs:comment
> **Object:** "The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes, either as a DateTime or as a textual string indicating a time period in ISO 8601 time interval format."

**Add**
> **Subject:** ceterms:temporalCoverage
> **Predicate:** rdfs:comment
> **Object:** "The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes."

**Note:** ceterms:spatialCoverage also (incorrectly) references ISO 8601, but that is to be handled in this issue: #372

**Comment by stuartasutton** [comment]
Nate, we need to look at all of the following properties so we aren't handling these date issues piecemeal:

```
ceterms:alignmentDate
ceterms:dateEffactive
ceterms:endTime*
ceterms:foundingDate
ceterms:startTime*
```
**With the exception of** `endTime` and `startTime`, all of these properties need their date range changed from `xsd:dateTime` to `xsd:date`. 

In other words, we leave `endTime` and `startTime` with `xsd:dateTime.

We also need to add `ceterms:endDate` and `ceterms:startDate` with a range of `xsd:date`. Then, where we are currently using `endTime` and `startTime`, we should use `endDate` and `startDate`. 

We currently have nothing that I can see that requires both the date and time...but we should not deprecate these date/time properties since they might be used in the future and we'd like to not have to add them back in after we've deprecated them.

I want to think more about removing references to ISO8601. The permissive breadth of the ISO standard does not mean it can't be referenced where a more constrained use is in operation.

**Comment by siuc-nate** [comment]
Thanks, Stuart. I have a separate issue setup for the date/dateTime range problem: #369

This issue is just about removing references to the ISO standard from the definitions/comments of CTDL properties as outlined above. I don't think it's necessary to include that reference anyway, as it conflicts with the definition provided by the xsd:date (and dateTime) ranges.

**Comment by siuc-nate** [comment]
Per our 4/7/2017 call:
The changes in the above comment: https://github.com/CredentialEngine/vocabularies/issues/370#issuecomment-292213482
will be implemented.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
