### ISSUE TITLE
CredentialAssertion, CourseCompletion, BadgeAssertion, and other learner records.

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/vocabularies#396]
New to this, so please point out any errors I make in this process.

In the area of learner records, a goal that I have is to be able to articulate that an individual:
- Has completed some class.
- Has acquired some credential.
- Has had some competency asserted.
- Has obtained some badge.
- Has completed some resource.
- Scored some value on some assessment.

Using a combination of specifications, we can get most of the way there:
(Forgive me if I left out your favorite specification)
- In OpenBadges, an assertion may be made about an individual possessing a badge.
- In CASS, an assertion may be made about an individual possessing a competency.
- In xAPI, individuals complete learning activities (which include assessments).
- In Caliper, Assessments and Assignables may be completed.
- And of course, in CTDL, CredentialAssertions indicate an individual has a credential.

Some gaps:

Is there a model we can use indicating that an individual has completed a course that anyone is aware of? I could imagine articulating this in a couple existing ways, but they are contrived cases. 

CredentialAssertion appears to be a placeholder. Are there plans yet for it?

Among most of the specifications listed above, individual identities appear to be rather disparate. Public keys, hashed identities, (Credential)Person objects, email addresses, etc are all used as identifiers with varying levels of anonymity. Is there a group working on how to create and protect learner records (that are meant to be protected)?

**Comment by siuc-nate** [comment]
Do you mean something like a transcript?

**Comment by Lomilar** [comment]
A transcript would work, assuming it is built out of records indicating the completion of courses. I presume an educational transcript would be a container for course completions.

**Comment by siuc-nate** [comment]
I don't know enough about transcripts to say for sure, but they seem to be the closest thing to a standardized way of communicating which courses a student has completed that I can think of. Is there in fact a (reasonably well-followed) standard/schema for transcript data?

**Comment by stuartasutton** [comment]
@Lomilar, in one sense you can say that [`certerms:CredentialAssertion`](http://credreg.net/ctdl/terms/CredentialAssertion) is a placeholder because there are no properties defined in CTDL with  the class as its domain. Since the scope of CTDL is to describe credentials (and their related entities) as *works*, there are no (current) plans for CTDL to flesh out  `certerms:CredentialAssertion`. The class is defined for two purposes: (1) to enable us to more clearly draw the distinction between the credential as work and the awarded credential; and (2) to be able to define the relationship between the CTDL specification and the Open Badges specification in this regard:

>CTDL : Credential ---> Open Badges : Badge Class
CTDL : CredentialAssertion ---> Open Badges : Assertion

Of course, the does not preclude others from declaring properties with `certerms:CredentialAssertion` as domain or creating awarded credentials and declaring them to be of the class `certerms:CredentialAssertion`.

**Comment by Lomilar** [comment]
Understood.

@siuc-nate: I surveyed a large number of schemas for Course Completion, and found hits in PESC (XML based schema) and CEDS (More of a database schema).

eTranscript, when it arrives, is supposed to be covering this (I think) and other forms of learner profile data.
