### ISSUE TITLE
Determine if CTDL Assessment Profile or Verification Profile Can Map to HR Open Standards CompetencyEvidence

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#410]
Need to determine if CTDL Assessment Profile or Verification Profile Can Map to HR Open Standards CompetencyEvidence.  

This is an excerpt from this document created by Bob Sheets as a summary of how HR Open Standards covers competency frameworks and statements https://docs.google.com/document/d/1ZKdV28r8pEkwBkxRAI6nxnDXO66-tt55xrSUE1xM9kM/edit?usp=sharing 

HR Open Standards Definition - CompetencyEvidence: CompetencyEvidence is used to capture information to substantiate the existance, sufficiency, or level of a Competency. CompetencyEvidence might include test results, reports, performance appraisals, evaluations, certificates, licenses, or a record of direct observation, such as a report given by a former supervisor or other employment reference.

**Comment by siuc-nate** [comment]
Based on our 6/1/3/2017 conversation:

These items appear to all be related to the relationships between competencies and other things, so there is no CTDL change to be made here.

We will schedule a meeting with HR Open Standards to discuss this further.

**Comment by siuc-nate** [comment]
@jkitchensSIUC can we close this issue?

**Comment by stuartasutton** [comment]
I would say that it can be closed. The HR properties identified by Bob in his accompanying document are all handled in the current ASN:

HR
`competencyID`  -- URI of the competency
`taxonmyID` -- URI of the competency framework
`competencyWeight` -- asn:weight
`competencyEvidence` (see discussion below)

The competencyEvidence property in the HR context makes sense because it points to an individual person's "evidence" for a competency. It has no applicability in CTDL or ASN because neither are concerned with an individual holder's evidence of anything.
