### ISSUE TITLE
Weights and/or Importance Levels with Competencies

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#414]
Weights and importance levels with competencies are included with DOL competencies directly related to occupations and HR Open Standards competency model includes them.  The DOL importance levels have multiple properties associated with an importance scale https://www.onetonline.org/help/online/scales.  This web page also had definitions on scales by domain the scale includes:

- Importance
- Level
- Relevance
- Frequency

The related calculations are also on this page https://www.onetonline.org/help/online/scales 

Does CTDL-ASN Support the weights and importance levels for each node on a competency framework? How does it map to HR Open Standards?

- Employers  use weights/importance levels.
- Test  books that certification bodies use can include weights.

**Comment by siuc-nate** [comment]
the AlignmentObject has a weight property that covers at least some of this.  We should discuss it further on Tuesday.

**Comment by siuc-nate** [comment]
@jkitchensSIUC @stuartasutton The importance levels within DOL are properties of the relationship between a given competency and an occupation - they aren't properties of the competencies themselves. The CredentialAlignmentObject's weight property can accomodate this as-is.

Can this issue be closed?

**Comment by stuartasutton** [comment]
We should keep it open because of the interplay with issue #413.

**Comment by stuartasutton** [comment]
I do not agree that the `ceterms:weight` cover property with CredentialAlignmentObject covers these. This needs discussion.

**Comment by siuc-nate** [comment]
Per our 8/8/2017 conversation:
We need to set aside some time to discuss this issue, and how it relates to #413.

**Comment by stuartasutton** [comment]
@jkitchensSIUC, just thinking out loud. In the absent discussion, the only scales above (and in the O*Net doc) that seem to me to be applicable are `importance` and `level` since `relevance` and `frequency` are aspects of the relationship between a `Task` and an `Occupation`; e.g.,

```
Task==relevanceTo==>Occupation
      value=30%
```

and

```
Task==frequencyTo==>Occupation
      value="Rarely"
```

With `importance` and `level`, Nate is correct that these terms define a relationship between a `Competency` and an `Occupation` and somewhat right in saying that we have `CredentialAlignmentObject` to handle such assertions. 

```
Credential==occupationType==>CredentialAlignmentObject
                             weight==>"50"
                             targetNode==>http://onet...../87654
                             targetNodeName==>"Bartender"
```

There really isn't a current property that definitively identifies this as "importance". It's certainly **not** `alignmentType` since it does not the refine relating predicate `occupationType`. It would need something like:

```
Credential==occupationType==>CredentialAlignmentObject
                                   importance==>"50"
                                   targetNode==>http://onet...../87654
                                   targetNodeName==>"Bartender"
```

The same would be true for `level` (`occupationLevel`).

```
Credential==occupationType==>CredentialAlignmentObject
                              level==>"71"
                              targetNode==>http://onet...../87654
                              targetNodeName==>"Bartender"
```

Creating such properties as `level` (defined per ONet) and `importance` (defined per ONet) would be somewhat necessary when we look at an `rdf:Statement` used where some third party makes the assertion in a `Map`:

![2017-08-14-maps](https://user-images.githubusercontent.com/2939046/29294559-cd9b33fe-8104-11e7-9286-34322235bb53.png)

Both `ceterms:level` and 'ceterms:importance` could be declared as subproperties of the existing `ceterms:weight`.

This last part on 3rd party mappings is related to issue #413.

**Comment by siuc-nate** [comment]
I'm really hesitant to use such broad terms as "level" and "importance" on their own as terms for such a highly specific use. I'd prefer they be two-word terms, something like "occupationImportance" and "occupationLevel" (though better terms may come from the definitions).

**Comment by stuartasutton** [comment]
Consider for 3rd party mappings:

> **URI:** `ceasn:competencyImportance`
**Label:** Competency Importance 
**Description:** Degree of importance of the competency to the occupation on a 1-5 scale.
**Type:** `xsd:integer`

> **URI:** `ceasn:competencyLevel`
**Label:** Competency Level 
**Description:** Degree, or point along a continuum, to which the competency is required or needed to perform an occupation on a 0-7 scale.
**Type:** `xsd:integer`

Note that O*Net "normalize" the level and importance scales for a consistent 0-100 score (see: https://www.onetonline.org/help/online/scales).

With additional thought, these might play a role as additional scale properties for `ceasn:competency` (current scales: `ceasn:weight` and `ceasn:complexityLevel`); however, they are different in character to the existing scales since `ceasn:competencyLevel` and `ceasn:competencyImportance` represent a scaled value of a relationship between a competency and something else (an occupation). That is not the case with the current scales on `ceasn:competency`.

**Comment by siuc-nate** [comment]
I think it makes way more sense to use either a 0-1 scale (as with weight) or a 1-100 scale (as with O*NET).  Arbitrary numbers like 1-5 or 0-7 (why 0-7?) would probably be normalized into something else anyway. Since we set the precedent with weight, I lean towards a 0-1 scale (and a range of xsd:float).

**Comment by stuartasutton** [comment]
Nate, O*Net does not use a 0-100 scale. That's a normalized scale done with the following formula:

> S = ( (O - L) / (H - L) ) * 100

where S is the standardized score, O is the original rating score on one of the three scales, L is the lowest possible score on the rating scale used, and H is the highest possible score on the rating scale used.

**Comment by siuc-nate** [comment]
Then I misunderstood when/where you said:
>Note that O*Net "normalize" the level and importance scales for a consistent 0-100 score (see: https://www.onetonline.org/help/online/scales).

Regardless, I think using a 0-1 scale makes more universal sense.

**Comment by stuartasutton** [comment]
It would be good to be able to merge any data input into these scales with data from O*Net. So we'd best use their non-normalized scales (1-5 & 0-7) for these properties or their normalized scale (1-100).

**Comment by siuc-nate** [comment]
If we use a 0-1 scale, that's easily converted to a 1-100 scale.  I'm trying to think about the bigger picture, beyond O*NET, for internationalization purposes, etc. - I would not want to base properties on a single entity/use case like this, particularly since conversion is easy.  O*NET's data can be normalized to a 0-1 scale while retaining data quality (it's a float, so the value can extend to multiple decimal points, whereas a 1-100 scale using only integers is slightly more rigid).

**Comment by stuartasutton** [comment]
I, too, am trying to think of a larger world--one in which getting buy-in on a single scale across a range of measurements is somewhat of a fool's errand. That's not to say that, like O*Net, disparate scales shouldn't be normalized for a specific context. But, if you are going to use another entity's scales, then use them as you find them and normalize.

**Comment by siuc-nate** [comment]
I don't believe we should bake the scale into the property unless the scale is something universal like a 0-1 (aka 0-100%) scale.  Failing that, we would need to define some way of defining both the number and the scale so that we don't end up with a CTDL property that only O*NET ever has any use for. 

Let O*NET extend CTDL for such a property if they really want to.

**Comment by siuc-nate** [comment]
Given that the various types of levels are properties of the relationship between the competencies and some other entity (i.e. occupations), they need to be accommodated in some entity other than competency. The question arises as to whether or not these properties would be a part of CTDL-ASN proper, or of some profile or extension that is specific to O*NET.

**Comment by siuc-nate** [comment]
Per our 7/17/2018 conversation:
Importance, Level, Relevance, and Frequency would be appropriate properties for Alignment Maps (i.e., domain = alignment of map), but are not useful for competency frameworks in a context that is separate from a particular application because importance and levels can be different for the same competency when related to a different occupation.  This is really an attribute of occupations, for instance, rather than competencies.
