### ISSUE TITLE
When to use hasPart and when not to use it

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#434]
The [`ceterms:hasPart`](http://credreg.net/ctdl/terms/hasPart) and [`ceterms:isPartOf`](http://credreg.net/ctdl/terms/isPartOf) properties have a usage note that needs to be removed or significantly revised. The mention of "embedded" should be removed and a revised comment focused on the fact that the partitive notion has to do with **constituent parts** of some thing. E.g., a book `hasPart` chapter and a chapter `isPartOf` a book. Someone else's chapter cannot be `isPartOf` my book.  So, someone else's certification may be required by my degree but it is not part of my degree...thus the imprecision of the notion of [embedded/nested](http://connectingcredentials.org/wp-content/uploads/2016/06/Glossary-of-Credentialing-Terms.pdf). 

In the [CTDL Guide](http://www.credreg.net/ctdl/handbook#requireCerts), we treat a required set of CompTIA certifications  for a degree (i.e. "embedded", or as Connecting Credentials says, "nested") as straight forward requirements described through [`CondiitonProfile`](http://credreg.net/ctdl/terms/ConditionProfile) because, like the "someone else's certification" noted above, they are **not constituent parts** of the degree for which they are required. However, the WorkIt record for the [Western Governors University's Bachelor of Science in Information Technology](https://credentialfinder.org/credential/6) which matches the Guide example circumstance exactly, uses [`ceterms:hasPart`](http://credreg.net/ctdl/terms/hasPart) for CompTIA certifications for which the University offers course work for student to prepare to sit for the required CompTIA examinations. 

Thus, I think, the json for the Western Governors University's Bachelor of Science in Information Technology in WorkIt incorrectly states:

```
 "ceterms:hasPart": [
        {"@id": "http://credentialEngineRegistry.org/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858"},
        {"@id": "http://credentialEngineRegistry.org/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31"},
        {"@id": "http://credentialEngineRegistry.org/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174"},
        {"@id": "http://credentialEngineRegistry.org/resources/ce-195F53A7-0635-46F6-9706-E3DDF881683F"},
        {"@id": "http://credentialEngineRegistry.org/resources/ce-C57948C2-6636-4ED3-9B51-BC5A9EC56D88"},
        {"@id": "http://credentialEngineRegistry.org/resources/ce-BB7F0B03-4430-43A1-9BAB-43E388F9C2CE"},
        {"@id": "http://credentialEngineRegistry.org/resources/ce-A28FFE42-70BB-462A-9D3B-FB4739BFB0B2"}
    ]
```

**Comment by siuc-nate** [comment]
We should discuss this on Tuesday.

**Comment by stuartasutton** [comment]
Agreed, Tuesday.

**Comment by siuc-nate** [comment]
Unfortunately, we didn't get to this one.  @jkitchensSIUC and I had some back and forth about it last week (hence my comment above), but we didn't arrive at a clear conclusion.  

My stance is based on my conversation with @stuartasutton last week - that the credentials in the "hasPart" section of the example should be associated via `requires` - though the details of this depend on exactly how those credentials relate.

Since the bachelor degree requires a learning opportunity, and it is that same learning opportunity (the degree program) which serves as the requirement for those other credentials, it is probably more correct to say that both the bachelor degree and the other credentials all _require_ the same learning opportunity.

If perhaps each of the credentials in the hasPart list require individual courses within the degree program (i.e., you don't have to finish the entire program to get one of the certificates), then you would probably need to define those courses as individual learning opportunities, set each as a requirement for its respective credential, then add all of those courses to the hasPart property of the degree program learning opportunity which is required by the bachelor degree credential. 

In other words:
```
//The Bachelor degree
{
	"@type": "ceterms:BachelorDegree",
	"ceterms:name": "Bachelor of Science in Information Technology",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp0" }
			]
		}
	]
}

//The Bachelor degree program
{
	"@type": "ceterms:LearningOpportunityProfile",
	"@id": "http://.../learningOpp0",
	"ceterms:name": "Bachelor of Science in Information Technology Degree Program",
	"ceterms:hasPart": [
		{
			{ "@id": "http://.../learningOpp1" },
			{ "@id": "http://.../learningOpp2" },
			{ "@id": "http://.../learningOpp3" }
		}
	]
}

//Courses for the degree program
{
	"@type": "ceterms:LearningOpportunityProfile",
	"@id": "http://.../learningOpp1",
	"ceterms:name": "Course 1"
}

{
	"@type": "ceterms:LearningOpportunityProfile",
	"@id": "http://.../learningOpp2",
	"ceterms:name": "Course 2"
}

{
	"@type": "ceterms:LearningOpportunityProfile",
	"@id": "http://.../learningOpp3",
	"ceterms:name": "Course 3"
}

//Certificates earned while completing courses within the degree program
{
	"@type": "ceterms:Certificate",
	"ceterms:name": "Certificate 1",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp1" }
			]
		}
	]
}

{
	"@type": "ceterms:Certificate",
	"ceterms:name": "Certificate 2",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp2" }
			]
		}
	]
}

{
	"@type": "ceterms:Certificate",
	"ceterms:name": "Certificate 3",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp3" }
			]
		}
	]
}
```

In this way, I think you correctly identify the _actual_ relationships between items. There is no direct connection at all between the degree and certificates you earn while pursuing the degree via pursuing its underlying program.  It may be simple marketing to say that "the degree includes a bunch of certificates", but that is not really what is happening - unless I am misunderstanding the situation, which is possible, since it is not terribly clear **exactly** how the certificates relate to the degree.

Note that the complexity above hinges on whether or not the certificates require the entire degree program to be completed, or if you could just complete some course or set of courses.  If you have to complete the whole program to earn any (and therefore all) of the certificates, then the graph is much simpler:
```
//The Bachelor degree
{
	"@type": "ceterms:BachelorDegree",
	"ceterms:name": "Bachelor of Science in Information Technology",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp0" }
			]
		}
	]
}

//The Bachelor degree program
{
	"@type": "ceterms:LearningOpportunityProfile",
	"@id": "http://.../learningOpp0",
	"ceterms:name": "Bachelor of Science in Information Technology Degree Program"
}

//Certificates earned upon completing the degree program
{
	"@type": "ceterms:Certificate",
	"ceterms:name": "Certificate 1",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp0" }
			]
		}
	]
}

{
	"@type": "ceterms:Certificate",
	"ceterms:name": "Certificate 2",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp0" }
			]
		}
	]
}

{
	"@type": "ceterms:Certificate",
	"ceterms:name": "Certificate 3",
	"ceterms:requires": [
		{
			"@type": "ceterms:ConditionProfile",
			"ceterms:targetLearningOpportunity": [
				{ "@id": "http://.../learningOpp0" }
			]
		}
	]
}
```

**Comment by stuartasutton** [comment]
@siuc-nate, first, the CompTIA (and other) certificates required by the degree program do not **require** any learning opportunity and it would be inappropriate to assert that they do--unless, of course, you ARE CompTIA. Second, while not absolutely clear to someone reading the degree program documentation, it does not appear to me that the course's **require** the certificates. All the courses say is that they **prepare** the student to sit for the CompTia exam. So, I think, absent a confirmation that your sense of it is correct (i.e., learning opportunity requires certificate), it's the degree is what requires the CompTIA certificates.

**Comment by siuc-nate** [comment]
Let me try to get this straight:

Degree -> requires -> Learning Opportunity (degree program)
Degree -> requires -> Certificate(s)
Learning Opportunity (degree program) -> preparationFor -> Assessment (CompTIA)
Certificate(s) -> requires -> Assessment (CompTIA)

Is that what you mean?

**Comment by siuc-nate** [comment]
Per our 8/23/2017 conversation, we will review this document:
https://docs.google.com/document/d/1zRHQeZN-O4_jMd3lq7rr8XH4ErFOLaiPEmGrntHn9rw/edit (Page 4/5)
We will determine which property(ies) need to be added to satisfy this use case.

**Comment by stuartasutton** [comment]
I am working on a proposal to clarify and refine the the definition of ceterms:hasPart and to include a set of new properties to more precisely cover credential connections as noted in the google doc above and in the [Connecting Credentials Glossary](http://connectingcredentials.org/wp-content/uploads/2016/06/Glossary-of-Credentialing-Terms.pdf). This will entail the addition of 4-6 new properties. I'm creating a Connecting Credentials project now here in github and a set of individual github issue entries for each of the new proposed properties.

**Comment by siuc-nate** [comment]
See Issue #454
