### ISSUE TITLE
Review and position proposed schema.org:Occupation type in CTDL context

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#442]
We need to review the new schema.org [Occupation type proposal](https://github.com/schemaorg/schemaorg/issues/1698) (vholland) for implications for (1) CTDL, and (2) our upcoming proposed Credential extension to schema.org.

In many ways, loose parallels can be drawn between the proposed Occupation type and O*Net in terms of binary mappings (e.g., occupation to skill) without the bells and whistles of refining scales.

**Comment by stuartasutton** [comment]
See also https://github.com/schemaorg/schemaorg/pull/1709/commits/7fea72a9f370ae243c7d725126bef04f86f055db

**Comment by siuc-nate** [comment]
I assume we don't want to start defining the requirements, qualifications, responsibilities, or skills as well? I certainly hope not. All we really need from this would be the occupationalCategory property and maybe some offshoot of the Occupation class as well, perhaps as a subclass of CredentialAlignmentObject (which we currently use to convey the same information).

**Comment by stuartasutton** [comment]
Nate, the reason we need to think about this is whether there are part of the schema entity that we handle through other profiles like Earnings that could be mapped.

**Comment by philbarker** [comment]
In terms of (2) the upcoming proposed Credential extension to schema.org: a schema:Occupation having schema:educationRequirements seems in the same area as wanting to make a link between occupations and the credentials that are required to practice that occupation (assuming there is a desire to be able to do that with the schema Credential extension). 

schema:educationRequirements, looks like a property that could usefully be refined (it's unusual for schema properties to be plurals, it looks like descriptive text is expected rather than specific terms as literals). It's an existing schema.org property, and so its addition as a property to Occupation doesn't really change much (I guess there would be a desire for the schema Credential extension to allow links to be made between job postings and credentials?)
