### ISSUE TITLE
Reviewing/clarifying range for ceterms:RevocationProfile, and ceterms:Renewal

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#444]
The range of ceterms:RevocationProfile includes all credential classes. 
For the editor, it was decided to only allow entry of this profile for licences and certifications.
The same decision was made for ceterms:Renewal. 

As we are developing the assistant API, the question arises on what input should be allowed. As well what guidance should be provided regarding the range. 

Should the range of these properties be changed?

**Comment by stuartasutton** [comment]
The [`ceterms:revocation`](http://credreg.net/ctdl/terms/revocation) property is the only property pointing to the `ceterms:RevocationProfile`](http://credreg.net/ctdl/terms/RevocationProfile). As you note, the domain of the `ceterms:revocation` property is all of the credential types. I don't think we can actually change the domain of `ceterms:revocation` to be only `ceterms:License` and `ceterms:Certification` simply because that decision has been made for the editor. Have we truly concluded that this restriction is universally applicable?

@cwd-mparsons, just to be certain, `ceterms:renewal`](http://credreg.net/ctdl/terms/renewal) property also has a domain of the full range of credentials. So, are you asking that the domains for `ceterms:renewal` should be also be reduced to reduced to `ceterms:License` and `ceterms:Certification`? My thoughts are the same here--no, unless we've truly concluded that this restriction is universally applicable.

**Comment by siuc-nate** [comment]
It is more convenient in general to have such properties be on all classes of credential, but we have already violated that in the case of the degreeConcentration/Major/Minor properties, which are only on Degree and subclasses thereof.

In this case, I'm not sure what other credential types might merit revocation or renewal, but it is probably worth discussing.

**Comment by stuartasutton** [comment]
@siuc-nate, discussion is in order. I don't think convenience is the driving factor. The issue is whether these properties have domain listings that invite errors. So, review is in order.

**Comment by siuc-nate** [comment]
Per our 8/23/2017 discussion:
We will leave revocation's domain alone, but add a comment:
**Add:**
> **Subject:** ceterms:revocation
> **Predicate:** dcterms:description
> **Object:** "Generally, revocation applies to certifications and licenses; however, it may also apply to other types of credential under extraordinary circumstances."

We will leave renewal's domain alone, but add a comment:
**Add:**
> **Subject:** ceterms:renewal
> **Predicate:** dcterms:description
> **Object:** "Generally, renewal applies to certifications and licenses; however, it may occasionally apply to other types of credentials."

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
