### ISSUE TITLE
Using ShEx and/or SHACL to validate RDF

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#448]
In mid-July, I sent and email regarding emerging standard ways to validate RDF data. Today, Dan Brickley opened an issue over on schema.org for discussion around validation of RDF. We should track these discussions.

https://github.com/schemaorg/schemaorg/issues/1715

My July message state:

>"The ShEx (Shape Expressions) community folks are nearing completion of their work on RDF validation. ShEx will make it possible to define shape expressions for the CTDL what will make it possible for the first time using a standard to validate RDF data. At some point, we'll want to be able to validate CER-conforming RDF data directly.  
>
>http://shex.io/

**Comment by stuartasutton** [comment]
Just an observation from yesterday's TAC call (2017-09-29). After the discussion of the new schema and application profile (AP)  management system and its auto-generated documentation pages and schemas, Phil asked about where ShEx and SHACL fit in the picture. *It's a significant question.*  If one outcome is the generation of a json schema for AP constraint validation of json data, why not generate ShEx and SHACL from the same constraint set for validation of RDF data?

**Comment by siuc-nate** [comment]
Depending on what the syntax of that is, it may be possible.  I intend to try to generate some kind of (more direct) serialization of the constraints as they are now, since Phil mentioned wanting to see them.

I should note that I have been running into significant difficulties implementing the "pointer" class(es) into the CTDL validation - everything else works, but since those are effectively nonexistent objects, I am trying to find a clean way to hack them in at the right point so that they are injected into the validation without breaking anything. It's proving quite difficult.

**Comment by stuartasutton** [comment]
Remind me of what ""Pointer" classes" means?

**Comment by siuc-nate** [comment]
That is the solution for pointing to an entity that does not exist in the registry, e.g., instead of
```
"ceterms:ownedBy": [ 
  { "@id": "ce-UUID" }
]
```
You use:
```
"ceterms:ownedBy": [
  { 
    "@type": "ceterms:CredentialOrganization",
    "ceterms:name": { "en": "Some Organization" },
    "ceterms:description": { "en": "Description text" },
    "ceterms:subjectWebpage": "http://someorganization.com",
    "ceterms:socialMedia": [
      "http://twitter.com",
      "http://facebook.com"
    ]
  }
]
```

Which means the validation JSON goes from:
```
"ceterms:ownedBy": {
  "type": "array",
  "properties": {
    "@id": {
      "type": "string",
      "format": "uri"
    }
  }
}
```
to something along the lines of:
```
"ceterms:ownedBy": {
  "type": "array",
  "properties": {
    "oneOf": [
      {
        "@id": {
          "type": "string",
          "format": "uri"
        }
      },
      {
        "@type": {
          "type": "string",
          "enum": [
            "ceterms:CredentialOrganization",
            "ceterms:QACredentialOrganization"
          ]
        },
        "ceterms:name": {
          "$ref": "#/definitions/ceterms:name"
        },
        "ceterms:description": {
          "$ref": "#/definitions/ceterms:description"
        },
        "ceterms:subjectWebpage": {
          "$ref": "#/definitions/ceterms:subjectWebpage"
        },
        "ceterms:socialMedia": {
          "$ref": "#/definitions/ceterms:socialMedia"
        },
      }
    ]
  }
}
```
which is pretty gnarly. I may be able to define the pointer class a different way and get away with using a `$ref` to it but that's probably outside the scope of what you're interested in.

Anyway, I have been trying, with various limited degrees of fruitfulness, to inject an phantom object like that into the schema validation. No such object, restricted to just those properties (and importantly, mandated to _not_ have an `@id` property), exists in the schema, so I have to create one on-the-fly using the constraint mechanisms I setup. I have been considering expanding those to be more accommodating of this; I had hoped to be able to do it with the existing triples-inspired mechanism (and may yet be able to).  

Another complicating factor is that each top-level thing could theoretically have a different set of properties used in its pointer version (for instance, only organizations use "socialMedia"), so I can't just do one template at the schema level and call it a day. Since I need to stay away from hard-coding anything about a given schema into the generator (since it needs to function for any schema), I am trying to keep it universal. It's very tricky, but I haven't exhausted all of the possible ways of doing it yet.

This also means that, in the context of validation, properties which point to top-level things can't benefit from declaring them to always be `@type: @id` in the `@context` either, since sometimes they are `@id` objects and sometimes they're pointers.

**Comment by stuartasutton** [comment]
Nate, I'm sorry if this is gnarly, obviously another instance where open and closed worlds collide; but, any resource in RDF can be expressed as either a URI referenced object or as a bnode. Obviously, the preference is for a URI referenced entity wherever possible even if that entity is not in the Registry; e.g., http://www.wikidata.org/entity/Q41506 (Stanford University). 

The image & table below is from my semantic web course at UW and illustrates the built-in boundaries of RDF and identifying resources:

![rdf_graph-0](https://user-images.githubusercontent.com/2939046/31100556-bacb9372-a77e-11e7-9e6b-d1e773fdf8f9.jpg)

Grammatical Part | URIref | Literal | bnode
---------------|--------------|-----------|-----------
Subject | X | | X |
Predicate | X | |  |
Object | X | X | X |

Thus in the absence of any resource being identified by URI, it can nevertheless be represented with a little descriptive information (name, website) in a bnode. That is true in RDF with anything...in our domain model, that would include everything that the gang refers to as  'top-level" entities. In fact, we do this all the time in the Registry with profiles and other entities in the model that have not been treated as "top-level". They are expressed as bnodes. So, in RDF, there is nothing unusual or necessarily wrong representing anything by means of a bnode.

Of course, you could enforce a Registry AP rule that says that no Organization, Credential, Learning Opportunity or Assessment can be referenced if it cannot be identified in the Registry by URI. In fact, the decision tree you introduced today could build in such a guarantee (included below) is enforced. *BUT* it would mean that referencing something like an organization's accreditor would be dependent on an impossible level of orchestration of entries a real chicken and egg problem.

* Quality assurance organizations could make no statements about entities (Organizations or Programs or Credentials or Assessments without those things being put into the registry by their controlling organizations; 
* Credentialing organizations couldn't say anything about their accreditation or other forms of quality assurance without quality assurance organizations having already entered their descriptions.

Stuart

-----------------
![credential publishing process](https://user-images.githubusercontent.com/2939046/31101805-1af3882c-a784-11e7-921a-ae86686fefae.png)
