### ISSUE TITLE
Walk through text fields in CTDL

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#450]
https://docs.google.com/spreadsheets/d/12P5lQyNa3KRxrO88BawqXbFCnvXjMCgwc8qfo-Il3TM/edit#gid=0

This lists every class, property, concept scheme, and concept in the schema along with its label, description, comment, and usage note. Each of these terms has two rows: one for the "current" set of values, and one that is left blank and is intended to hold any changes we may make.  There is also a column to indicate when something was changed (for easy visual scanning later) and a column for notes.

There is also a blank row between each pair of rows to make it a little easier to navigate (hopefully).

See the "CostProfile" row (row 60) and the "Diploma" row (row 92) for examples of the intended usage.

**Comment by stuartasutton** [comment]
Per our conversation on Tuesday's team call (2017-10-03), I have gone through the https://docs.google.com/spreadsheets/d/12P5lQyNa3KRxrO88BawqXbFCnvXjMCgwc8qfo-Il3TM/edit#gid=0 sheet with definition revisions and (rather generously) marked those I think "pass" in green. That turned out to be a significant number. There are two categories remaining for our joint review:

1. Those that were not touched at all; i.e, nothing in the "Changes" row; and
2. Those shaded in grey -- usually means that the changes were rooted in 1 or more comments in the advisory board member survey comments; comment number(s) noted in "Notes" column.

The process we agreed to follow on Tuesday's call is:

1. After I made this now-complete pass, marking in green those I thought were a "pass", together we'd maker two passes through those definitions noted above in 1 & 2; 
2. In our first shared pass, we'd not spend any amount of time word smithing definitions that still need it but keep moving through low-hanging fruit; and
3. Make a final pass through discussing and revising the previously noted few that are more gnarly.

**Comment by siuc-nate** [comment]
These changes have been taken care of and noted in history tracking.
