### ISSUE TITLE
Process and formatting of classes like credential, and organizations without an @id

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#451]
@stuartasutton 
As has been discussed in the past, we will have a scenario where someone will want to publish that, say their organization accredits a credential, but doesn't know the @id URI, or even if one exists. 
The approach for this was format the property, and require all of:
- Name
- Description
- SubjectWebpage
For organization, we were going to optionally include SocialMedia. An asserted by would appear as:
ceterms:assertedBy: [
{
	ceterms:name: "Credential Organization - for for condition asserted by",
	ceterms:description: "Credential Organization - for for condition asserted by",
	ceterms:subjectWebpage: [		{	
			@id: "http://example.com?t=CredentialOrg"
		}	]
	}
],
The question arose, as to whether a type should be included, like
ceterms:assertedBy: [
{
        @type: "ceterms:CredentialOrganization",
	ceterms:name: "Credential Organization - for for condition asserted by",
	ceterms:description: "Credential Organization - for for condition asserted by",
	ceterms:subjectWebpage: [		{	
			@id: "http://example.com?t=CredentialOrg"
		}	]
	}],
Now the organization that is publishing the latter may not know whether to use ceterms:CredentialOrganization or ceterms:QACredentialOrganization.
Nate suggested that in this case we could use **ceterms:Agent**.
Thoughts?

The scenario is more complicated for references to a credential (assuming we want to include the @type). 
Say, a user is publishing one or more credentials as a target credential, it would be much more convenient to reference the super class of ceterms:Credential, rather than having to include the appropriate credential type.

ceterms:targetCredential: [
{
	@type: "ceterms:Credential",
	ceterms:name: "Target Credential for a condition profile",
	ceterms:description: "Target Credential for a condition profile",
	ceterms:subjectWebpage: [	{
		@id: "http://example.com?t=targetCredentialForCP"
	}	]
}
],

So:
- Do we want to always include a type with these 3rd party references
- Can we use the super class in references to credentials and organizations?

**Comment by stuartasutton** [comment]
Yes, we absolutely need to include the @type. That was my primary concern in the beginning of this whole conversation--i.e., we have some thing and were reluctant to identify it as what it is just because it did not have a record in the registry. As for credentials, I feel the same, its @type should identify what it actually is. In other words, we shouldn't default to the superclass Credential when we know its type is one of the subclasses.

**Comment by cwd-mparsons** [comment]
@stuartasutton 
I have added the @type as being required. 
Do you think that it would be an issue, or complication for someone publishing to know if a reference to an organization should be CredentialOrganization or QACredentialOrganization.

Are there any issues for a heterogeneous list of entities that are only @ids under, say owns, or offers?
The list for the latter properties could be any of assessment, learning opportunities, or credentials.

**Comment by stuartasutton** [comment]
As for the first question, I think there will likely be lots of people who will be confused about the distinction between a CredentialOrganization and QACredentialOrganization...at least for a while. 

As for the question of only @ids, I'm not quite sure what you are asking. Do you mean we'd have a list of @id that look like the following?

```
"ceterms:offers": [
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174"
    },
  ],
```
As far as RDF and Linked Data are concerned, there's absolutely no problem with this because, in a Linked Data context, those URIs could be resolved and additional data brought back and presented as part of the record.  In such a context, resolving URI reduces the amount of data entry. If that can't happen in the system, then URIs alone don't tell a user much.

@cwd-mparsons, I kind of think I've not really answered your question :-(.

**Comment by siuc-nate** [comment]
I think what @cwd-mparsons is asking is if, in the list above, one item was a credential, another an assessment, and the third a learning opportunity, would it be better to include a `@type` with each object, e.g.:
```
"ceterms:offers": [
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858",
      "@type": "ceterms:Certificate"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31",
      "@type": "ceterms:AssessmentProfile"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174",
      "@type": "ceterms:LearningOpportunityProfile"
    },
  ],
```
The idea being that a consuming system would know ahead of time how to process the resulting data, which can save time and code trying to interpret the result's type before further processing. Otherwise you end up with a more complex process (assuming you're using a strictly typed language that doesn't let you directly check the `@type` value of the retrieved data prior to deserialization):

1. Create a generic key-value pair container object, such as a `Dictionary<string, string>` in C#
2. Fetch the data as a JSON-encoded string
3. Deserialize the data to that object
4. Check the value of its `@type` type property, and based on that:
5. Deserialize the data a second time, only now you deserialize it to the actual class you want to use
6. Call the appropriate methods and pass the data
7. Continue as normal

vs:

1. Fetch the data as a JSON-encoded string
2. Based on the `@type` value that accompanied the `@id` in the original reference:
3. Deserialize the data to the appropriate class
4. Call the appropriate methods and pass the data
5. Continue as normal

The savings are useful but not _super_ significant. In either case you would probably need the same structure (a series of `if` blocks, or a `switch` block) to figure out what to do with the data. This would also require more code on the part of the publisher to ensure the `@type` value is always included, and I fear our publishing documentation is tricky enough as it is for developers to absorb.

My other worry is that if you include anything other than an `@id` for something in a JSON-LD document, it's not clear whether or not that document is then supposed to be interpreted as _the_ document rather than just a link to something (but then that may not be a concern in realistic/practical terms). In other words, I'm not sure if it's in line with the JSON-LD spec to include more than just the `@id` in a reference.

We could make it required to provide a `@type` any time you would otherwise use just a `@id` to enforce the decision if we decide to go down this road.  I am hesitant to do so.

**Comment by siuc-nate** [comment]
@stuartasutton @cwd-mparsons In looking through the examples in the JSON-LD spec ( https://json-ld.org/spec/latest/json-ld/ - particularly the section on type coercion ), it seems that anything which is an identifier is technically supposed to have a `@type` of `@id`. I'm not 100% certain as to whether or not we can do that implicitly (I think this came up a long time ago, when we began working on serializations for the registry), but I don't think we can have valid JSON-LD if reference properties don't have a `@type` of `@id`.

**Comment by stuartasutton** [comment]
@siuc-nate , if `@id` has to be paired with a `@type`, that would make sense...how difficult is an issue I'll need to leave to you folks implementing.

**Comment by siuc-nate** [comment]
It would seem that it does, but I'm not sure if it needs to be explicitly included.  I probably should have made that a separate point from my larger (and more thread-relevant) point that we can't use some _other_ `@type` value with our `@id` objects.

**Comment by stuartasutton** [comment]
I think I am confused? What "other `@type`"?

**Comment by siuc-nate** [comment]
The examples I raised in my [earlier comment](https://github.com/CredentialEngine/vocabularies/issues/451#issuecomment-327516179)

**Comment by stuartasutton** [comment]
If `@type` is included with `@id` in this context, I get some odd behavior in conversion to RDF. Assume we have the following (built on the example above):

```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "@language": "en-US"
  },
  "@type": "ceterms:BachelorDegree",
  "@id": "http://lr-staging.learningtapestry.com/resources/ce-CB8EB8D0-208D-4DA0-9F50-7003F8A39ED6",
  "ceterms:alternateName": [
    "BS Information Technology"
    ],
  "ceterms:offers": [
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858",
      "@type": "ceterms:Certificate"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31",
      "@type": "ceterms:AssessmentProfile"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174",
      "@type": "ceterms:LearningOpportunityProfile"
    }
  ]
  }
```
This converts to the following turtle:

```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://lr-staging.learningtapestry.com/resources/ce-CB8EB8D0-208D-4DA0-9F50-7003F8A39ED6> a ceterms:BachelorDegree ;
    ceterms:alternateName "BS Information Technology"@en-US ;
    ceterms:offers <http://lr-staging.learningtapestry.com/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174>,
        <http://lr-staging.learningtapestry.com/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858>,
        <http://lr-staging.learningtapestry.com/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31> .

<http://lr-staging.learningtapestry.com/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174> a ceterms:LearningOpportunityProfile .

<http://lr-staging.learningtapestry.com/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858> a ceterms:Certificate .

<http://lr-staging.learningtapestry.com/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31> a ceterms:AssessmentProfile .
```

which oddly round-trips back to json-ld as:

```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-CB8EB8D0-208D-4DA0-9F50-7003F8A39ED6",
      "@type": "ceterms:BachelorDegree",
      "ceterms:alternateName": {
        "@language": "en-US",
        "@value": "BS Information Technology"
      },
      "ceterms:offers": [
        {
          "@id": "http://lr-staging.learningtapestry.com/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858"
        },
        {
          "@id": "http://lr-staging.learningtapestry.com/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31"
        },
        {
          "@id": "http://lr-staging.learningtapestry.com/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174"
        }
      ]
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31",
      "@type": "ceterms:AssessmentProfile"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858",
      "@type": "ceterms:Certificate"
    },
    {
      "@id": "http://lr-staging.learningtapestry.com/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174",
      "@type": "ceterms:LearningOpportunityProfile"
    }
  ]
}
```
While the code looks odd, it graphs OK:

![servlet_8132955732169646285](https://user-images.githubusercontent.com/2939046/30171113-c979bf62-93a5-11e7-9686-cba12884b90b.png)

**Comment by stuartasutton** [comment]
This thread has become very garbled. There two totally different scenarios that have been conflated here:

(1) [lastest] Should straightforward URIrefs in the json-ld also include an `@type`; and
(2) when describing a a top-level entity with no URI in the registry, does it have a `@type` even where there is no `@id` to point to.

First is "no" and the second is "yes".

**Comment by cwd-mparsons** [comment]
@stuartasutton Yes, we are implementing this as you suggest
