### ISSUE TITLE
Consider adding hasTopChild as subproperty of hasChild

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#474]
Consider adding `ceasn:hasTopChild` with a domain of [`ceasn:CompetencyFramework`](http://credreg.net/ctdlasn/terms/CompetencyFramework). Then remove `ceasn:CompetencyFramework` from the domain of [`ceasn:hasChild`](http://credreg.net/ctdlasn/terms/hasChild) (and clean up its usage note). 

Currently, ASN uses `ceasn:hasChild` for both denoting the top children of a the framework and the children of competencies. This change makes clear the distinction between the two uses--as explained in the current usage note for `ceasn:hasChild`. It also makes it clear that the competency *does not necessarily* list all of its children--only the top children of taxon paths and may list all as 'top' in a flat list.

**Comment by siuc-nate** [comment]
If I'm interpreting you correctly, what you want to do is go from this:
![image](https://user-images.githubusercontent.com/21346519/31085183-1b198e6e-a75c-11e7-81e4-9d39a682edd3.png)

to this:
![image](https://user-images.githubusercontent.com/21346519/31085210-27805dae-a75c-11e7-90f5-5d2fcfe31528.png)

Right? 

I find it interesting that we have "isPartOf" but no "hasPart" to serve the reverse purpose. Should we complete the graph with something like this?:
![image](https://user-images.githubusercontent.com/21346519/31085235-321b7a46-a75c-11e7-9895-48bec8446d61.png)
Note the additional change of "isTopChildOf" - this would clean up the domains and ranges and keep our language consistent:

hasTopChild:
- Domain: CompetencyFramework
- Range: Competency

isTopChildOf:
- Domain: Competency
- Range: CompetencyFramework

hasPart:
- Domain: CompetencyFramework
- Range: Competency

isPartOf:
- Domain: Competency
- Range: CompetencyFramework

Now the framework can reference all of its children and its top level children, and all of the competencies can be related back to the framework their in, while also describing their place in the heirarchy.

**Comment by stuartasutton** [comment]
@siuc-nate, the goal of adding a new `hasTopChild` was to eliminate any seeming need to use the `hasPart` for linking a `ComptencyFramework` to all of its competencies. That was never the intention of `hasPart` with `ComptencyFramework`, thus the tortured usage note. I really don't see the need for the `isTopChildOf` since it is quite adequately handled by the current `isPartOf` to which `isTopChildOf` adds nothing but pointless symmetry.

**Comment by siuc-nate** [comment]
@stuartasutton It seems strange to me to use "isChildOf" for both:
`Competency -isChildOf-> Competency` and
`Competency -isChildOf-> CompetencyFramework`

Yet only use "top" one way in the other direction:
`Competency -hasChild-> Competency`
`CompetencyFramework -hasTopChild-> Competency`

As I indicated in my previous note, part of the goal is to have one range per property, as well.  Hence the "isTopChildOf" addition.

I assume you meant tortured usage note for "isPartOf" - we currently do not have a "hasPart" property.  Would you prefer to drop isPartOf altogether? The equivalent functionality can probably be handled with meta properties. 

I would also want to consider whether or not we're being consistent with SKOS, since the more 1:1 we can make the alignment of our properties and usage with SKOS properties and usage, the easier time we'll have when it comes to making use of, documenting, and explaining both competencies and vocabularies among ourselves and to partners.

**Comment by stuartasutton** [comment]
I meant `hasChild` has a tortured usage note that is solved through `hasTopChild`. Nate, we need to cleave close to ASN. 

Nate, nowhere is `Competency==isChildOf==>Competency`

**Comment by siuc-nate** [comment]
In the schema, [isChildOf](http://credreg.net/ctdlasn/terms/isChildOf) has a domain of Competency and a range of both CompetencyFramework and Competency, which may be part of the problem.

However, even if the range were just CompetencyFramework, it would still be odd to have "hasTopChild" and "isChildOf" - I would rather use "hasTopChild" with "isTopChildOf" - again, this keeps the ranges clean and prevents the sort of confusion we are bumping up against in this thread. It also makes it easier to explain: "hasChild/isChildOf deals with competency-to-competency connections; hasTopChild/isTopChildOf deals with competency-to-framework connections."

**Comment by stuartasutton** [comment]
Nate, no. The `isTopChildOf` solves nothing and serves no purpose. All competencies have an `isPartOf` property linking them to their framework and so do top competencies. I'm not seeing any reason for the hasPart from competency to all of its member competencies.

**Comment by siuc-nate** [comment]
I gave up on hasPart after your initial rejection. It can be handled through meta properties.

As for `isChildOf`, currently `Competency -isChildOf-> Competency` does exist in the schema. Is that something we'd remove? Together with adding `hasTopChild` instead of `hasChild` for CompetencyFramework-to-Competency connections, that would result in:
![image](https://user-images.githubusercontent.com/21346519/31097881-7cf36e1e-a786-11e7-94df-5eba4cd8be01.png)
which means you'd use `hasChild` to get from one Competency to another, but you could only use `isChildOf` to get from a Competency to a Framework.  This seems very counterintuitive and awkward to me. It also means a Competency can't point to its parent, which is something I think we should avoid.

And, to reiterate: `isTopChildOf` would help solve the problem of avoiding confusion and allowing for these connective properties to have a single class in their range, which is maybe not the best justification, but it isn't "no purpose".

Anyway, if the changes you want ultimately boil down to the ones depicted in that graph, then they look like this:

**Remove:**
> **Subject:** ceasn:isChildOf
> **Predicate:** rdfs:rangeIncludes
> **Object:** ceasn:Competency

**Remove:**
> **Subject:** ceasn:hasChild
> **Predicate:** rdfs:domainIncludes
> **Object:** ceasn:CompetencyFramework

**Create:**
> **URI:** ceasn:hasTopChild
> //Other properties TBD
> **rdfs:domainIncludes:** ceasn:CompetencyFramework
> **rdfs:rangeIncludes:** ceasn:Competency

Is this correct?

**Comment by stuartasutton** [comment]
Nate, for the past 17 years, the following has been the ASN with the exception of creating hasTopchild as a subproperty of hasChild.

![2017-10-3-asn](https://user-images.githubusercontent.com/2939046/31099442-da62f8d2-a77a-11e7-98b7-07090ae1776b.png)

**Comment by siuc-nate** [comment]
That graph makes more sense. One note:
When you said:
>Nate, nowhere is Competency==isChildOf==>Competency

I have been trying to determine whether you meant we should remove it (because it shouldn't be there, but it is) or if it _should_ be there (which it already is).  Judging by the graph above, we would _instead_ remove `CompetencyFramework` from the range of `isChildOf`, which solves the awkward usage problem in my previous post. 

So that being the case, is this what you want?:
**Remove:**
> **Subject:** ceasn:isChildOf
> **Predicate:** rdfs:rangeIncludes
> **Object:** ceasn:Competency**Framework**

**Remove:**
> **Subject:** ceasn:hasChild
> **Predicate:** rdfs:domainIncludes
> **Object:** ceasn:CompetencyFramework

**Create:**
> **URI:** ceasn:hasTopChild
> //Other properties TBD
> **rdfs:domainIncludes:** ceasn:CompetencyFramework
> **rdfs:rangeIncludes:** ceasn:Competency

**Comment by stuartasutton** [comment]
Yes.

**Comment by stuartasutton** [comment]
### Actions

#### Remove:
**Subject:** ceasn:isChildOf
**Predicate:** rdfs:rangeIncludes
**Object:** ceasn:CompetencyFramework

#### Remove:

**Subject:** ceasn:hasChild
**Predicate:** rdfs:domainIncludes
**Object:** ceasn:CompetencyFramework

#### Create:

**URI** ceasn:hasTopChild
**Label** Has Top Child
**Definition** Top-level child competency of a competency framework.
**Domain Includes** ceasn:CompetencyFramework
**Range Includes** ceasn:Competency

**Comment by siuc-nate** [comment]
These changes have been made.
