### ISSUE TITLE
Two errors in term history tracking (cs:createdDate & cs:ChangeSet)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#491]
Nate, somewhere between issue #238 and implementation, one property ([cs:createdDate](http://purl.org/vocab/changeset/schema#createdDate)) was dropped and one class [cs:ChangeSet]{http://purl.org/vocab/changeset/schema#ChangeSet) was redeclared in our [meta namespace](http://credreg.net/meta/terms/ChangeSet#ChangeSet) when it need not have been. 

### Changing namespace declaration to [cs:ChangeSet](http://purl.org/vocab/changeset/schema#ChangeSet)

We need to change the namespace declaration for `ChangeSet` from our `meta` namespace to the `cs` namespace and deprecate our [meta:ChangeSet](http://credreg.net/meta/terms/ChangeSet#ChangeSet). The `cs` definition is as follows:

> "The encapsulation of a delta between two versions of a resource description"

**Comment by stuartasutton** [comment]
***Sorry, hit 'update' too soon...***

Nate, somewhere between issue #238 and implementation, one property ([`cs:createdDate`](http://purl.org/vocab/changeset/schema#createdDate)) was dropped and one class [`cs:ChangeSet`]{http://purl.org/vocab/changeset/schema#ChangeSet) was redeclared in our [`meta namespace`](http://credreg.net/meta/terms/ChangeSet#ChangeSet) when it need not have been.

### Changing namespace declaration to cs:ChangeSet

We need to change the namespace declaration for `ChangeSet` from our meta namespace to the `cs` namespace and deprecate our `meta:ChangeSet`. The `cs` definition is as follows:

> "The encapsulation of a delta between two versions of a resource description."

### Adding cs:createdDate:

We need to add the [`cs:createdDate`](http://purl.org/vocab/changeset/schema#createdDate) to the range of [`cs:ChangeSet`](http://purl.org/vocab.org/changeset/schema#ChangeSet) as illusutrated in issue #238. Otherwise, we have no way knowing when a particular change was made or actually sequencing changes since we don't use [`cs:precedingChangeSet`](http://purl.org/vocab/changeset/schema#precedingChangeSet). The date should be the release date of the change.  If not practical to do this retrospectively, we should include the propertyt for changes going foward.

**Comment by siuc-nate** [comment]
I have updated the system for serializing history:
- Fixed an error that resulted in only the current release's history showing for any given item
- Added `cs:createdDate` (uses the date of the matching schema release)
- Now uses `cs:ChangeSet` instead of `meta:ChangeSet`
- Now uses `ceterms:subjectWebpage` instead of `meta:moreInformation`
- Now uses `skos:changeNote` instead of `meta:hasChangeSet`
- Removed `meta:ChangeSet`
- Removed `meta:moreInformation`
- Left `meta:hasChangeSet` alone for now (it may be useful in homogenizing the JSON-LD and Turtle serialization structures as a `{ "@container": "@graph" }` term, but it may also be unnecessary)
- Changed `meta:ChangeNote` to `meta:ChangeHistory`
- Updated JSON and Turtle serializations of history terms:
  - JSON-LD serialization is now just a named graph of `cs:changeSet`s
  - Turtle serialization begins with a `meta:ChangeHistory` node (but this could be removed)
- Reworked URL structure for history terms:
  - Now uses /termhistory/ instead of /release/ for JSON and Turtle serializations, i.e., `http://credreg.net/[schema abbreviation]/termhistory/[term prefix]/[term value]/` 
  - Now supports addition of a change set ID at the end of the URI to retrieve individual change sets
- Updated links in pages and serializations

Example URIs:
- Release history page (unchanged): http://credreg.net/ctdl/release/
- Alternative Condition JSON-LD (all changes): http://credreg.net/ctdl/termhistory/ceterms/alternativeCondition/json
- Alternative Condition JSON-LD (specific change set):
http://credreg.net/ctdl/termhistory/ceterms/alternativeCondition/json/873b6f6b-d40e-4740-a627-567bb16ba850
- Alternative Condition Turtle (all changes): http://credreg.net/ctdl/termhistory/ceterms/alternativeCondition/turtle
- Alternative Condition turtle (specific change set): http://credreg.net/ctdl/termhistory/ceterms/alternativeCondition/turtle/873b6f6b-d40e-4740-a627-567bb16ba850

@stuartasutton Please let me know what you think, and see if you spot any errors.

Thanks.
