### ISSUE TITLE
CTDL-ASN: drop competencyText, update description to take its place

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#494]
Per our 11/22/2017 call:

ASN:
- description is used in ASN to hold the text of the competency
- comment is used in ASN to provide supplemental information

CTDL-ASN:
- competencyText is used in CTDL-ASN to hold the text of the competency
- description is used in CTDL-ASN to provide supplemental information
- comment is used in CTDL-ASN to provide supplemental information

CTDL-ASN does not need all three properties.  In order to facilitate smoother mapping between CTDL-ASN and ASN, we determined that we should:

- Drop the ceasn:competencyText property (deprecate? remove outright? remove domains? is this schema considered official/released? @stuartasutton  please chime in here)
- Update the definition (and/or comment) of ceasn:description property to reflect is use as both a description of a competency framework and the holder of the text of a competency

Tagging: @stuartasutton @Lomilar

**Comment by stuartasutton** [comment]
@siuc-nate, after looking at this over the weekend, I don't think we need to make these changes. The [`competencyText`](http://purl.org/ctdlasn/terms/competencyText) is quite clear. The [`description`](http://purl.org/ctdlasn/terms/description) property is not needed with [`Competency`](http://purl.org/ctdlasn/terms/Competency) since [`competencyText`](http://purl.org/ctdlasn/terms/competencyText) provides the text and [`comment`]() elaborates where necessary. Then [`description`](http://purl.org/ctdlasn/terms/description) can be limited to [`CompetencyFramework`](http://purl.org/ctdlasn/terms/CompetencyFramework).

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove:**
> **Subject:** ceasn:description
> **Predicate:** rdfs:domainIncludes
> **Object:** ceasn:Competency

**Remove:**
> **Subject:** ceasn:competencyText
> **Predicate:** vann:usageNote
> **Object:** This property should be used to provide the actual text of the competency statement. To provide a description of the competency other than the text itself, use the description property.

**Add:**
> **Subject:** ceasn:competencyText
> **Predicate:** vann:usageNote
> **Object:** This property should be used to provide the actual text of the competency statement. To provide information about the competency other than the text itself, use the comment property.

**Comment by stuartasutton** [comment]
I don't think so.

**Comment by stuartasutton** [comment]
Since we are just getting really started with the ceasn, let's not track these changes.

**Comment by siuc-nate** [comment]
Understood. This can be closed, then.

**Comment by stuartasutton** [comment]
Yes
