### ISSUE TITLE
Missing from hasCostManifest & hasConditionManifest 

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#505]
Nate, I think the [CTDL context](http://credreg.net/ctdl/schema/context/json) is missing two declarations that are causing things to be represented as strings when converted to RDF turtle:

```
"ceterms:hasConditionManifest": {
   "@type": "@id"
},
````

and

```
"ceterms:hasCostManifest": {
   "@type": "@id"
},
```
Using the [American National Standards Institute (ANSI)](https://credentialengine.org/publisher/organization/55/American_National_Standards_Institute_(ANSI)) record in the editor, I find the following block of code for `hasConditionManifest` and `hasCostManifest`:

```
"ceterms:hasConditionManifest": [
    "https://credentialengineregistry.org/resources/ce-237ab290-aed5-4f96-977e-8054499d8b41",
    "https://credentialengineregistry.org/resources/ce-de18b975-2ca9-4579-883e-845c07a41109",
    "https://credentialengineregistry.org/resources/ce-9d1f691b-e40b-4b94-91ba-d54c138b4267",
    "https://credentialengineregistry.org/resources/ce-d5fc9941-2b6d-4de1-b686-d70249234e04",
    "https://credentialengineregistry.org/resources/ce-1504d260-2522-4807-8788-445cf1fb4e4c"
  ],
  "ceterms:hasCostManifest": [
    "https://credentialengineregistry.org/resources/ce-fc8bce96-58fe-4e49-a788-bd2836703ee1",
    "https://credentialengineregistry.org/resources/ce-affff215-10bb-4c68-b3fb-06493f49342f",
    "https://credentialengineregistry.org/resources/ce-cf56e74b-f7d1-4ce9-af2c-f3fce826d93a",
    "https://credentialengineregistry.org/resources/ce-12d6c694-fc83-453b-be77-c15c19f7df38",
    "https://credentialengineregistry.org/resources/ce-d9cd1283-dbfb-495a-99ac-e14c4f9eafb3",
    "https://credentialengineregistry.org/resources/ce-bef6d3d4-a3b5-46ea-b6da-25273cd11bae",
    "https://credentialengineregistry.org/resources/ce-4525a4f7-520f-41b9-bea7-a406370c0296",
    "https://credentialengineregistry.org/resources/ce-a0d14aab-6ef5-47aa-83d9-479519237d99",
    "https://credentialengineregistry.org/resources/ce-c3cbe1f5-d8eb-4826-89c9-42621f76fbb9",
    "https://credentialengineregistry.org/resources/ce-047ddd11-e1b6-4a31-8de4-478b1d371219",
    "https://credentialengineregistry.org/resources/ce-0a851e86-56b4-46ea-b082-8df6679a8b9b",
    "https://credentialengineregistry.org/resources/ce-5d665f9c-2984-4d9b-b4f1-473962aa5b06",
    "https://credentialengineregistry.org/resources/ce-de42aa7f-ce62-4388-8dc2-77d8a82c0291",
    "https://credentialengineregistry.org/resources/ce-e6aab55e-baf5-477d-965f-f3b1e003afd4"
  ],
```

When translated to RDF turtle, I get URI's treated as strings which indicates the omissions from `@context` file:

```
<ceterms:hasCostManifest>https://credentialengineregistry.org/resources/ce-5d665f9c-2984-4d9b-b4f1-473962aa5b06</ceterms:hasCostManifest>
<ceterms:hasConditionManifest>https://credentialengineregistry.org/resources/ce-de18b975-2ca9-4579-883e-845c07a41109</ceterms:hasConditionManifest>
```

**Comment by cwd-mparsons** [comment]
@stuartasutton Nate is out until the new year. I can look into adding the referenced hasConditionManifest, and hasCostManifest to the schema. 
The Json validation schema has these properties defined as strings. Is the latter still correct, that is does only the schema have to change?

**Comment by stuartasutton** [comment]
Michael, to be clear, it's the json context file that needs the two additional declarations for `hasConditionManidest` and `hasCostManifest`. Since these are object properties that point to things, they can't be strings; so, the json validation schema would appear to be wrong.

**Comment by cwd-mparsons** [comment]
Stuart
These used to be objects, but Nate changed them to strings as part of the October updates. I don't see an entry in the History that might indicate why the change was made. 
I can make the necessary changes to revert to using objects. As well, I will have to check if there are other properties that were changed to strings, and should in fact be objects.

**Comment by stuartasutton** [comment]
That's peculiar. They still show objects (`CostManifest` and `ConditionManifest`) as range in the terms definitions:

>http://purl.org/ctdl/terms/hasConditionManifest
http://purl.org/ctdl/terms/hasCostManifest

Without them, there's no way to connect organizations to their manifests...hmmm.

**Comment by siuc-nate** [comment]
It took me a bit to work through what happened, I think I figured it out - we had originally been handling these the same as other properties that point to standalone objects.  That is, we had been enabling them to either be an `@id` object or a reference/pointer object.  However, we later decided it didn't make sense to offer that, and changed them to only permit `@id`s.  So in the validation schema, they look like this:
![image](https://user-images.githubusercontent.com/21346519/34136914-a6fa86aa-e42d-11e7-91f4-cbd415c88d68.png)
which translates, ultimately, to an array of strings (which are the `@id` URIs).  So that much is correct.  However, in the process of making that change, I must have forgotten to ensure they still had a `@type` of `@id` in the context. That designation is determined dynamically, if I remember right, so that we wouldn't have to remember to set it up for every property that points to an object. I think there was a way to override it, but I don't immediately recall what it was. If I come across it, I'll fix it and describe further.

**Comment by stuartasutton** [comment]
Thought you were on holiday :-)

**Comment by siuc-nate** [comment]
I was - Mike let me know there was an issue so I decided to check it out.

Anyway, the fix I was thinking of applied only to things where the profile of the Registry had been applied, so I had to devise a new method to force the `@type` to be `@id` for selected properties regardless of profile (or not).  I have done so, so this has now been fixed:
http://credreg.net/ctdl/schema/context/json?releaseID=20171027

Note that I have applied this to the following properties, since all of these will always be URIs rather than (potentially) pointer objects:
- ceterms:commonConditions
- ceterms:commonCosts
- ceterms:hasConditionManifest
- ceterms:hasCostManifest
