### ISSUE TITLE
Use of inLanguage property for data that exists in multiple languages

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#506]
Reference: https://trello.com/c/rW8CJ7PP/203-will-there-be-an-option-for-multiple-languages-right-now-you-can-only-select-one-primary-language-microsoft-has-requested-the-ab

Summary: In the publisher, Microsoft wants to be able to select multiple languages for the inLanguage property; however, the description of that property strongly suggests this should be single-select. 

Does this imply that we need a second property to indicate other languages that something is offered in?

**Comment by stuartasutton** [comment]
(I don't seem to have access to the trello card)

Nate, I **think** it is the latter because I **think** Microsoft wants to indicate that they offer a credential in multiple primary languages but are submitting a single description of the credential in English and want to indicate the other primary language versions. While it seems odd to me that they don't included metadata records in those other languages so native speakers could find them, the request is certainly not unreasonable. Anyway they want to indicate `otherLanguageVersion`. 

This does present a problem with values for things like `subjectWebPage` if, in fact each of those language versions has a web presence. It's when there are things like this, that one metadata description of the credential per language version is really more appropriate.

**Comment by siuc-nate** [comment]
Per our 1/22/2018 conversation:
This can be solved by allowing multiple values for the `ceterms:inLanguage` property.  `ceterms:inLanguage` defines the primary language for a resource, so if a resource is offered in multiple languages, then each of those would be a resource with one of those primary languages.

**Comment by siuc-nate** [comment]
To be handled in https://github.com/CredentialEngine/WORKIT-web-site/issues/11
