### ISSUE TITLE
MainJurisdiction is defined as multi-value but description states as primary

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#516]
@stuartasutton 
The definition of mainJurisdiction is:

> Primary geographic or political region in which the credential is recognized as applicable or in which an organization has recognized authority to act.

However, it is defined as multi-value:
![image](https://user-images.githubusercontent.com/26332112/36940188-dbe5cfda-1f03-11e8-9fa4-803c9049b5ab.png)

We had made the decision to only allow a single value in the publisher and registry assistant - under the concept of the registry profile. As partners start to use the API, they will use the CTDL definitions. I was reviewing an assessment published by NOCTI to the sandbox and saw that main jurisdiction was defined as a list. So:
- should this property be defined as single value
- or, should the API be updated to only allow a list
- or, should the API allow either, and publish to the registry as a list

**Comment by stuartasutton** [comment]
Couple of what might seem odd questions, Mike: (1) what's the multiplicity of the [`jurisdiction`](http://credreg.net/ctdl/terms/jurisdiction#jurisdiction) property in the Registry Profile; and (2) does NOCTI in the data you are looking at use the  [`jurisdictionException`](http://purl.org/ctdl/terms/jurisdictionException) properety.

**Comment by siuc-nate** [comment]
The original reasoning/structure is/was:
Multiple `jurisdiction`s, each with one `mainJurisdiction` and 0-n `jurisdictionException`s to that main jurisdiction.  

It may be more practical to allow multiple mainJurisdictions and assume that any exceptions will be within them, rather than try to enforce it (which I don't think we do anyway).

**Comment by stuartasutton** [comment]
Nate, you target what I was wondering about--instances of `jurisdiction` that support a pairing of main and exception. Thus the `jurisdiction` property would be the multi-valued property since the intention was to interpret the `JurisdictionProfile's` `mainJuruisdiction` in the context of exceptions, not that it was a single primary location.

**Comment by siuc-nate** [comment]
Approaches:
1. Leave the existing structure as-is
2. Make `mainJurisdiction` a multi-value field
3. Make `mainJurisdiction` a multi-value field **and** make `jurisdiction` a single-value field
4. Deprecate `jurisdiction` and `JurisdictionProfile` and add all properties currently in the domain of `JurisdictionProfile` to the domains of all classes that currently have `jurisdiction` in their domain

Option 2 would be the easiest to implement (and apparently is already the case in terms of the validation), but it would enable redundancy in terms of multiple JurisdictionProfiles each with multiple mainJurisdictions.  This may not be a real problem.

Thoughts?

**Comment by siuc-nate** [comment]
Per our 4-10-2018 call:
- We will update the profile to make mainJurisdiction a single-value field.

**Comment by siuc-nate** [comment]
This has been taken care of.
