### ISSUE TITLE
Adding json icon access to encoding to /publisher/

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#517]
Can we do the same thing with the json-ld icon with the /publisher/ that we did with the viewer. People in editing may have just as much need to see underlying encoding as someone at the viewer.

**Comment by siuccwd** [comment]
We did have a process to format an entity as Json on the publisher detail page, but it was very slow (8-10 secs) so I disabled the process until we can improve the performance. The finder uses the downloaded payload from the registry, so there is no processing necessary to format the data (since already in tht target JSON-LD).

**Comment by cwd-mparsons** [comment]
We did have a process to format an entity as Json on the publisher detail page, but it was very slow (8-10 secs) so I disabled the process until we can improve the performance. The finder uses the downloaded payload from the registry, so there is no processing necessary to format the data (since already in tht target JSON-LD).

**Comment by stuartasutton** [comment]
Thanks, Mike. In the end, even a bit of a wait is better than not being able to get there.

**Comment by siuc-nate** [comment]
We can probably bring it back as an AJAX thing.  I'll look into it when I get the chance.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @siuc-nate this needs to be a Trello card rather than a GitHub issue.  Please add a Trello card for this and close this issue.

**Comment by cwd-mparsons** [comment]
Added trello card:
https://trello.com/c/7UCDKELD/534-adding-json-icon-access-to-encoding-to-publisher
