### ISSUE TITLE
targetNodeName is required for a CredentialAlignmentObject, which will be an issue publishing competencies

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#518]
@stuartasutton Once we cut over to CASS based competencies, we will only be publishing the competency Uri in the TargetNode property of a CredentialAlignmentObject. However, targetNodeName is a required property of CAO. 
We could include the targetNodeName as a convenience, or this property would have to be removed as required, or some other action.

**Comment by stuartasutton** [comment]
@cwd-mparsons, @siuc-nate & @jkitchensSIUC, the required/required if available properties on [`CredentialAlignmentObject`](http://credreg.net/registry/policy#mindata_credentialalignmentobject) are a bit wacky--`targetNodeName` should not be required.  While `targetNodeName` is sometimes found with competency frameworks, it is more frequently not used. With concept schemes, the `targetNodeName` property usually contains the concept label "e.g., Cybernetics" and the `targetNodeDescription` contains the definition of the concept. 

Because of the nature of the alignment object, I don't think that there should be any properties in the required category and that  `targetNodeName` should be moved to required if available.

### BIG QUESTION

Now, I want to ask you a BIG, BIG question. You say that once you switch over to CASS, you will only be publishing the `targetNode` property's URI for competencies. That makes good RDF/Linked Data sense, but absolutely no sense with `CredentiialAlignmentObject` since the circumstance does not trigger a `CredentiialAlignmentObject` at all.  In other words, why are you doing this (using `targetCompetency` as an example):

`targetCompetency`===>`CredentialAlignmentObject`===>`targetNode`===>{*Some competency*}

when you could simply do this:

`targetCompetency`===>{*Some competency*}

Note that the properties that have `CredentialAlignmentObject` in range like [`targetCompetency`](http://purl.org/ctdl/terms/targetCompetency) also support direct reference of a `Competency` when there is no need for an intervening `CredentialAlignmentObject`.

**Comment by stuartasutton** [comment]
Per the BIG QUESTION, the same is true if a `Concept`. If all you are doing is referencing using the concept's URI, then no [`CredentialAlignmentObject`](http://credreg.net/registry/policy#mindata_credentialalignmentobject) is needed.

**Comment by siuc-nate** [comment]
I believe we've been including the name because we haven't encountered a situation where we didn't have it handy already, ans it makes examining the data easier.  While I agree that we only need the URI, technically, I am hesitant to switch to it without thinking through the impacts it would have.

**Comment by stuartasutton** [comment]
Nate, I only raised the "question" because Michael said that was what we were doing at the top of the thread.

**Comment by stuartasutton** [comment]
Sorry to bring this up here, but aren't we doing a zoom session this AM?

**Comment by stuartasutton** [comment]
Regardless of the "Big Question", the `targetNodeName` should not be required but rather required if available. That leads `CredentialAlignmentObject` to not having any required properties.

**Comment by siuc-nate** [comment]
Per our 3/9/2018 call:

The solution is to change targetNodeName from being required to required if available in the registry policy and validation.

**Comment by siuc-nate** [comment]
I have updated the profile and the policy page.
