### ISSUE TITLE
Add Credential, Assessment, and Learning Opportunity to the domain of audienceType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#525]
Currently, the http://credreg.net/ctdl/terms/audienceType property is only associated with ConditionProfile and CostProfile.  In those contexts, it defines the audience for which the condition or cost applies.

It probably makes semantic sense to also enable describing the audience for which the Credential itself (or assessment, or learning opportunity) applies.

Note: Scott identified this as a desired "best practice" addition to the data.

**Comment by cwd-mparsons** [comment]
While it makes sense to be able to describe a target audience, audienceType seems problematic:
![image](https://user-images.githubusercontent.com/26332112/37543467-b6a72350-292f-11e8-85a9-b6517a03b27e.png)

A credential for:
* a citizen  (same for non-citizen)
   * covered by jurisdiction
  * citizen of what
* same for resident/non-resident
* former student
  * of what, why
* full time/part time
  * this makes sense with conditions/costs not for creds, etc
* member/non-member
   * of what

Also with a wide range of concepts, people will just include every property, instead of only indicating exceptions.

**Comment by siuc-nate** [comment]
Per our 3/23/2018 call:
- "This Credential applies to [audience type]" and "This set of requirements for the Credential apply to [audience type]" are semantically different statements
- We will add audienceType to Credential, Assessment, and Learning Opportunity
- We will update the definition of audience Type from
"Type of credential seeker for whom the particular condition or cost is applicable; select from an existing enumeration of such types."
to
"the type of credential seeker for whom the entity is applicable; select from an existing enumeration of such types."

**Comment by stuartasutton** [comment]
@siuc-nate I think we are waiting for a signal from @jkitchensSIUC per your sentence: "@jkitchensSIUC will follow up with Scott to confirm the intent of this issue."

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
