### ISSUE TITLE
Staging server update error

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#550]
@cwd-mparsons, I know that you had these problems corrected...I saw it in an earlier email. But since I got the following from the staging server, I wasn't sure what's happening. These have to do with the `@graph` and the properties outside it:

`/resources/` instead of /`graph`/, CTID assigned, and `@type` assigned.

```
{
  "@id": "https://staging.credentialengineregistry.org/resources/ce-cb8eb8d0-208d-4da0-9f50-7003f8a39ed6",
  "@type": "ceterms:BachelorDegree",
  "@context": "http://credreg.net/ctdl/schema/context/json",
  "ceterms:ctid": "ce-cb8eb8d0-208d-4da0-9f50-7003f8a39ed6",
  "@graph": [
    {
      "@id": "https://staging.credentialengineregistry.org/resources/ce-cb8eb8d0-208d-4da0-9f50-7003f8a39ed6",
      "@type": "ceterms:BachelorDegree",
      "@context": "http://credreg.net/ctdl/schema/context/json",
      "ceterms:ctid": "ce-cb8eb8d0-208d-4da0-9f50-7003f8a39ed6",
      "ceterms:name": {
        "en": "Bachelor of Science in Information Technology"
      },
```

AND

```
{
  "@id": "https://staging.credentialengineregistry.org/resources/ce-036d082d-d80e-41a7-99a0-2d63a4ad3a4a",
  "@type": "ceterms:CredentialOrganization",
  "@context": "http://credreg.net/ctdl/schema/context/json",
  "ceterms:ctid": "ce-036d082d-d80e-41a7-99a0-2d63a4ad3a4a",
  "@graph": [
    {
      "@id": "https://staging.credentialengineregistry.org/resources/ce-036d082d-d80e-41a7-99a0-2d63a4ad3a4a",
      "@type": "ceterms:CredentialOrganization",
      "@context": "http://credreg.net/ctdl/schema/context/json",
      "ceterms:ctid": "ce-036d082d-d80e-41a7-99a0-2d63a4ad3a4a",
      "ceterms:duns": "129936902",
      "ceterms:fein": "841383926",
      "ceterms:name": {
        "en": "Western Governors University"
      },
```

**Comment by cwd-mparsons** [comment]
@stuartasutton I visited the following URL (from the above example):
https://staging.credentialengineregistry.org/graph/ce-cb8eb8d0-208d-4da0-9f50-7003f8a39ed6
and I get the following (@id, @graph, and context only at the root level): 
![image](https://user-images.githubusercontent.com/26332112/46829681-0474fe80-cd64-11e8-9486-dabce5ec1798.png)

Actually I now see the problem. I didn't re-import the updated data into the staging finder after I made the aforementioned corrections. The staging import is running now. Should be done in the next hour or so.

**Comment by stuartasutton** [comment]
:-)

**Comment by cwd-mparsons** [comment]
Sorry lost track of time. The import has been completed.

**Comment by stuartasutton** [comment]
@cwd-mparsons, this output looks good with the following exceptions. 

#### Repetition of `@context`:
The `@context` is correctly placed outside the `@graph` -- although, please, please, put at the top and not at the bottom of the code!!.  `@context` is then repeated ***unnecessarily*** inside the `@graph`.

#### Inclusion of `ceterms:framework` in alignment objects:
This might also interest @siuc-nate. I've never noticed that we do not include the URIref to the framework (`ceterms:framework`) in instances of `ceterms:CredentialAlignmentObject`. This is likely a universal issue.

So, instead of 

```
     "ceterms:agentType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "orgType:Postsecondary",
          "ceterms:frameworkName": {
            "en": "OrganizationType"
          },
          "ceterms:targetNodeName": {
            "en": "Postsecondary Educational Institution"
          }
        },
```

it should be 

```
     "ceterms:agentType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:targetNode": "orgType:Postsecondary",
          "ceterms:framework": "orgType:",
          "ceterms:frameworkName": {
            "en": "OrganizationType"
          },
          "ceterms:targetNodeName": {
            "en": "Postsecondary Educational Institution"
          }
        },
```

**Comment by siuc-nate** [comment]
Regarding the reference to the framework for controlled vocabularies, I don't think we can get away with using the shorthand URI as-is.  Currently `orgType:` would expand to `http://credreg.net/ctdl/vocabs/orgType/` (which throws an error when you try to resolve it), rather than `http://credreg.net/ctdl/terms/OrganizationType`.

I could update the system to redirect from `http://credreg.net/ctdl/vocabs/orgType/` to `http://credreg.net/ctdl/terms/OrganizationType`, which may be useful in other cases too. Would that work?

**Comment by cwd-mparsons** [comment]
@stuartasutton 
The repetitive @context was in an inherited base class, which is now removed.
re: @context first
This is the case in the artifacts published most recently.  When serializing, we have been using an alphanumeric contract resolver. So with new artifacts, the @context is first, but the @id is last. 
For now I exclude the latter resolver, and use the default.

**Comment by stuartasutton** [comment]
Just so both the graph URIref and the `@context` are at the very top of the file, that's great. It's not intuitive to have some of the declarations outside the graph at the top of the file and others at the bottom. Not incorrect, but not the best form.

**Comment by cwd-mparsons** [comment]
I updated the API add ceterms:framework. 
Following is an example (I only did a couple for now).
https://staging.credentialengineregistry.org/graph/ce-14525aea-57c5-4f5a-8f1c-bdc95c7f8b9b

**Comment by stuartasutton** [comment]
OK, @siuc-nate, too much going on here. First, we should be talking `http://purl.org/ctdl/vocabs/orgType/` and not `http://credreg.net/ctdl/vocabs/orgType/`. 

When I have the following: `orgType: <http://purl.org/ctdl/vocabs/orgType/>.` prefix, and then have a value of `orgType:`, it should resolve to `http://purl.org/ctdl/vocabs/orgType/`...which is perfectly legal.

**Comment by siuc-nate** [comment]
Yes, I agree, but I'm talking about what happens when you resolve the PURL `http://purl.org/ctdl/vocabs/orgType/`.  Right now it returns an error message. I'm asking whether it should instead redirect to `http://credreg.net/ctdl/terms/OrganizationType/` so that a consuming system gets JSON back instead of an error.

In other words, right now we have:
`orgType:` expands to ->
`http://purl.org/ctdl/vocabs/orgType/` redirects to ->
`http://credreg.net/ctdl/vocabs/orgType/` resolves to ->
`[error]`

I'm asking if we instead should have:
`orgType:` expands to ->
`http://purl.org/ctdl/vocabs/orgType/` redirects to ->
`http://credreg.net/ctdl/vocabs/orgType/` redirects to ->
`http://credreg.net/ctdl/terms/OrganizationType/` resolves to ->
`[JSON data]`

**Comment by stuartasutton** [comment]
Maybe will seem tangential, but what's returned by http://credreg.net/ctdl/terms/OrganizationType/? Am I getting html or json-ld? Or is it negotiated?

**Comment by siuc-nate** [comment]
Right, sorry, my mistake - that URL returns HTML, not JSON. The JSON equivalent would be 
[http://credreg.net/ctdl/terms/OrganizationType/json](http://credreg.net/ctdl/terms/OrganizationType/json) 

But I guess my more (semantically) important question/point is that `http://credreg.net/ctdl/terms/OrganizationType` is the canonical actual URI for that concept scheme whereas `http://credreg.net/ctdl/vocabs/orgType/` is just a prefix that is intended to have concept's (shorthand) URI appended to it.

So right now the user isn't getting the "real" URI for the concept scheme, they're getting a prefix intended to be a part of a URI for a concept.  If the concept-less URI (`http://credreg.net/ctdl/vocabs/orgType/`) instead redirects to the "real" URI for the scheme (`http://credreg.net/ctdl/terms/OrganizationType`), then is there anything invalid about that? Any down sides? It seems like that would be more correct in terms of giving the user what they need or what they're looking for than an error message would be.

**Comment by stuartasutton** [comment]
I think I am hopelessly confused. Maybe during our meeting tomorrow we can go over this. But here's a quick question: What is the URI you'd give to someone who asks for the URI for the concept "Postsecondary Educational Institution"? And, what you you tell them was the URI for that concept's concept scheme?

**Comment by siuc-nate** [comment]
Postsecondary Educational Institution:
http://credreg.net/ctdl/vocabs/orgType/Postsecondary

Organization Type vocabulary:
http://credreg.net/ctdl/terms/OrganizationType

The issue boils down to one using
`/ctdl/terms/[term name]`
and the other using
`/ctdl/vocabs/[concept scheme shorthand]/[concept shorthand]` 
since
`/ctdl/vocabs/[concept scheme shorthand]`
(with no concept shorthand) returns an error.

`http://credreg.net/ctdl/terms/OrganizationType` returns HTML data.
`http://credreg.net/ctdl/vocabs/orgType/Business` returns HTML data.
`http://credreg.net/ctdl/vocabs/orgType/` returns an error.

`orgType:Business` expands to
`http://purl.org/ctdl/vocabs/orgType/Business` which redirects to 
`http://credreg.net/ctdl/vocabs/orgType/Business` which returns HTML data.

`orgType:` expands to
`http://purl.org/ctdl/vocabs/orgType/` which redirects to 
`http://credreg.net/ctdl/vocabs/orgType/` which returns an error.

If I change it so that 
`http://credreg.net/ctdl/vocabs/orgType/` (with no concept shorthand appended) redirects to
`http://credreg.net/ctdl/terms/OrganizationType/` then the user (or the consuming system) will not encounter an error.
