### ISSUE TITLE
Add an isicV4 property

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#591]
We currently have an [`naics`](http://purl.org/ctdl/terms/naics) property for industry code covering North America. We should also add an `isicV4` code [1]-[2] (following schema.org that has both [3]) for international numbers. It should have the same domains as our `naics`.

See: https://github.com/schemaorg/schemaorg/issues/1698#issuecomment-477881620

[1] https://en.wikipedia.org/wiki/International_Standard_Industrial_Classification
[2] https://unstats.un.org/unsd/publication/seriesm/seriesm_4rev4e.pdf
[3] https://schema.org/isicV4

**Comment by WeaverStever** [comment]
@stuartasutton

Both https://schema.org/Person and  https://schema.org/Organization already has the naics and isicV4 properties.  The [naics](https://schema.org/Person) types are Organization and Person, while the [isicV4](https://schema.org/isicV4) types are Organization, Person and Place.

While Industry Classifications are relevant to Persons, Occupational Classifications are more important imho.  This because occupations generally cross industry classifications on a one to many relationship.

My comment that you linked above was in response to a comment where the https://pending.schema.org/Occupation only includes the occupational categories for the North American SOC and the person would prefer the ISCO international classification system. Basically, I suggested we provide two properties, specific to each occupational classification system, instead of just the one property -- https://pending.schema.org/occupationalCategory with the SOC preference written into the description.

**For Occupational Classifications:** 
The ISOC can be found here (08 is current).
https://www.ilo.org/wcmsp5/groups/public/@dgreports/@dcomm/@publ/documents/publication/wcms_172572.pdf

The NAICS / SOC  can be found here (2010 is current)
https://www.bls.gov/soc/

**Also, for Persons, or Occupations** we might want to consider including a property for the CIP (Classification of Instructional Programs).  For instance, the Computer Science discipline now has 38 CIP codes, i.e. specialty degree programs / fields of study.
https://nces.ed.gov/ipeds/cipcode/Default.aspx?y=55

**Comment by siuc-nate** [comment]
@stuartasutton to verify:
**URI:** ceterms:isicV4
**Label:** ISIC Revision 4 Code
**Definition:** The International Standard of Industrial Classification of All Economic Activities (ISIC), Revision 4 code for a particular organization, business person, or place.
**Domain:** ceterms:Credential (and subclasses), ceterms:CredentialOrganization, ceterms:QACredentialOrganization
**Range:** xsd:string

Correct?

**Comment by stuartasutton** [comment]
Correct!

**Comment by siuc-nate** [comment]
I'll also include that it's an equivalent property to schema:isicV4.

**Comment by stuartasutton** [comment]
Yes!

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
