### ISSUE TITLE
Drop ceterms:purposeType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#602]
When we dropped the Intended Purpose vocabulary (#87), we missed the ceterms:purposeType property.  This, too, is (and has been) vs:unstable, so it should just be dropped as well.

**Comment by cwd-mparsons** [comment]
We have no reference to purposeType in use by the API, finder or publisher.

**Comment by stuartasutton** [comment]
Yes, we've struggled from the beginning about the validity of asking the provider of a Credential to identify the intended purpose(s) of the holder. 

However, please understand that the LAST reason to drop a term or a vocabulary is that it has not been used in Registry records. We have no means of knowing, with ANY certainty, whether it has been used otherwise on the Web (or the dark web).

**Comment by siuc-nate** [comment]
Per our 6-4-2019 meeting:
It makes sense to drop (not deprecate) this property.

**Comment by siuc-nate** [comment]
This has been done in pending CTDL and noted in the history tracking.
