### ISSUE TITLE
Rules for publishing ceterms:Classification for occupation, job, task, and workRole 

### ISSUE THREAD

**Issue by mparsons-ce** [CredentialEngine/vocabularies#789]
ceterms:Classification has a range of Concept, without referencing a specific concept scheme. 
I added the latter to the publishing API as a list of CredentialAlignmentObjects. The thought at the time was the latter would provide flexibility, so that a concept that was not in the registry could be referenced.
However:
- Should any concept referenced always exist in the registry

If the latter is true, then I would update the API to require a list of CTIDs

**Comment by siuc-nate** [comment]
@stuartasutton It means we could've been using bnodes for things like competencies and concepts where none existed, instead of embodying their data in a CredentialAlignmentObject.

Regarding the issue itself, are there action items for the October release? This seems to be more of a policy thing than a schema thing.
